language: r
cache: packages
pandoc_version: 2.9.2.1

addons:
  apt:
    packages:
    - ghostscript

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

secure: "N5bMFHNnuvo2oGiDnXyzEpoGSmmo4sIyITdqey7d3AyqSp3gGocwJ4bz4u8MMlxmJGyVJIMotYYMdt9PP5qCDGeFpuuJZc/iKhsFxlSvweBePFjdCgA0reGsjAbSzuVx5vjncWVENfCzRTs/y5CYoggOjEgyZfMsb63U6Nq4wDN3BKSnwhDekhGHsBIRkR8h+SAdMUEgkqK5FIc+Q4EgURm+6v1fPIVPjm13PaBpOhvTKmnu6Ez671+NJHfu0+MZJ/lDjRVwV7YP6STSnZjkoM2cztKRalxHLcz7SLWxqHcBoJeA+VPDbD1NBXM7JzhvVMfweqvHNoM+av2x2ymmmkGA2F7BePX3I4oVN3T+H2rbcXxP4GzEPDiQH4sow1QFfLX8BHqxFXrQQoelaMp+ya7odjcaaQsR6h1gy5vZzew5lhgz60Ad9UFUV8QGjTeXS5NS/DR+rS2EgA3PBm4ozalC8ERcI52nTKzigPHpMDEM7zpPW9U3hb4YjKwg3rPmxLTSp0Nk4gd04P4wRTzljsFp6z/MlPdkIWAqOa277SFwkYH0uD19Cl303g/fhf11wARTRo+8JSznN1pju1SVrh3DqEYC+1d6zXWOD7ZXbl98gKmVx4BVa4m8IUOV0eK7LJRcR790qbbAxn16ldixnaFqvMbsm2IFqFNLHEEs3X8="
