# Introduction {#intro}

Later than the present time is always imaginary. We don’t know the future but we anticipate it. Anticipation as here understood includes two mandatory components: a forward-looking attitude and the use of the former’s result for action (Poli, 2017). The future does not actually exist. Therefore, hunting for futures run directly into the obstacle that by definition the future cannot exist in the present. And yet, the future plays a role in the present. How can something does not exist have an impact? An answer to this problem is the idea of anticipation. The future does not exist in the present but anticipation does. The form the future takes in the present is anticipation (Miller, 2017).

Anticipation is also vital for companies and organizations that want to develop convenient solutions to people’s problems and expectations that might emerge in the future. To do this, the future consumer and technology trends are anticipated by doing extensive researches. Depending on these anticipations, some of the existing products/services are being updated or new products/services are being developed to respond to future needs of society.

I give an applied course called **RHI460 Advertising Project** at Anadolu University Faculty of Communication Sciences, and its content is based on the emerging consumer and technology trends. The aim of the course is to encourage students to think creatively about the future needs and expectations of the society. After an extensive analysis of emerging trends, each of them write scenarios for the future. Later on, they form groups and develop innovative ideas that might serve the needs and expectations of the future consumers.

This book, which is one of the outputs of the course, is co-created by the students. Each chapter is a future scenario that is based on a specific theme and a scenario archetype.

**Themes**

The major trends we have discussed in classroom-2020 are listed as: Power of the crowd, individualization, urbanization, environmental issues, big data era, medical advances, offline experiences, play everywhere, betterment, connected, privacy concerns, disadvantaged groups, and security issues.

**Scenario Archetypes**

We used the six scenario archetypes framework of Fergnani & Song (2020). In their article they list six archetypal images of the future, which are; Growthy & Decay, Threats & New Hopes, Wasteworlds, The Powers that Be, Disarray, and Inversion.

I hope you enjoy reading these future scenarios written by young minds.

_Naim Çınar(Ph.D)_
_Anadolu University_
