--- 
title: "Lost in Galaxy"
author: "Bahtiyar Eminoğlu"
---
# Lost in Galaxy
by _Bahtiyar Eminoğlu_

**Abstract** 

> _Ramy is an everyday worker on the government. His job is to quality check a variety of products changed daily, inspecting them by the video stream of the security cams, but Ramy would start to get bored this underqualified job for him and start to quest the system. Newly developed technologies were not pleasing, and the feeling of long loneliness started him to be drawn into the galaxy._

“A hundred years,” said the professor and waited a bit. “A hundred years was the lifespan of an average human two centuries ago. Now, thanks to new AI management the average human lifespan is almost two hundred years, and two centuries ago human’s biggest importance was their health. We are caring about your health, so you could go on…” Another workday starts with this unimportant boring AI propaganda, I just cannot listen anymore. I am constantly asking myself that “What I’m doing?” with my life, with my relations, and what will I do years later? If it is the same quality control bullshit, I will hang myself without a doubt. Probably those AI-integrated government drones would not let me even do that. I heard once that a man from Fonrade just thinks of killing himself and before he goes to his window the FRPD (Fonrade Robotic Police Department) raids his house and arrest him acting against the Pro-Life law. So, if my intentions get more intense any moment some Robo-polices could be up to my door. It is not living anymore, and you cannot be dear to die neither. The working screen is loaded. I am a current worker of the Governmental Quality Standards Institute. All I do is watching some CCTV of some companies and check if their product quality retains the government’s expectations. The funny thing is, years ago a friend of mine told me that the companies send us some kinda video that was recorded years ago, again and again, just changing the dates. It gets funnier when you think more because if they send me the same video with different dates, I could not define if it is the same or different. When I think more about this, I am realizing that there is no window, no natural light source, it is indistinguishable from one to another. Today’s company is a children’s stationery manufacturer. Watching as the one blue eraser comes from the production line to the weighing and it is always at the same weight. A thousand eraser called as a party, and in every party, an eraser will select randomly and gets examined to see if it is having any hazardous elements that can harm children or having any defect or see the color of the eraser checks the company’s standards. Subject #986755 checks fine, subject #987542 checks fine, subject #989635 checks fine too… I am getting bored as hell, but I am sure that like I control those erasers, someone was controlling me too. So, I am taking my notes and think different things to try to keep my mind safe. Subject #990136 is fine, “What should I eat today?” Subject #991247 is fine, “What is on telly today?” Subject #992683 is fine, “But I am not, though.” Subject #993548 is fine, “why I am so alone?” Subject #994587 is fine, “Maybe I was not fair to Jane.” Subject #995621 is fine, “I wonder where she is now?” Subject #996852 is fine, “Or what she is doing?” Subject #997159 is fine, “Could we be together?” Subject #998020 is fine “Why all the things happened this way?” Subject #999626 is fine, then an automatic message popped out “Congratulations! Your work is done, for today. Thank you for your contributions to our community!” #Subject Ramy is not fine, #Subject Ramy is confused, #Subjesct Ramy is sad… 

I close my computer and get up from my chair. The computer said, “AppleSoft Corp. wishes you a good day, see you tomorrow!” The only communication that I have for today was the two messages send me automatically from the server. I just lay down to my bed and open the telly, some stupid show was on. “Microchips right, who is here loves microchips? It is something that helps our life I guess, but not on the planes apparently” Everybody starts laughing, “The flight attendant comes and says “Sir, can you please shut down your microchips?” And I just say, “Wish I know how to do it?” The usual situation, right? I wish the AI would find a solution to this. It will be like (In a robotic sound) “I am the AI system bleep-bloop, you have no right to take a flight.” Everybody laughs harder. “Thank you! Thank You! I am Garry Samefeld and have a good evening everyone.” Credits rolls and after that, there is a sponsor message, “This show is sponsored by Laugh-AI, it will be hilarious with artificial intelligence when you are not so intelligent.” Everybody still laughing and the show ends. Now the commercials start. “Next week Human VS. Nature VS. AI: Who would win?”, “The Treehouse Builders AI: Your favourite treehouse building show is back! And now with the new AI improved designs.”, “Do you want a perfume that does everything you desire? Tell us your desires and we will make it happen with our newly developed AI system. Come to us, New Delphine AI Beauty inc.” I really get bored with this stuff. I reach out to my Blu-Ray disc collection box. I found a disc that was a gift from Jane, we both love this movie “On the Waterfront”. We watched this movie together maybe a dozen times, maybe more. New AI movies are not as real as these old movies. Scripts are awful, nobody cares about acting and there are no artistic directions. A stone-cold machine writes and directs 90% of movies and series. All series become the same thing after all. The AI takes all the good bits from the old movies and breaks down to some little scenes, pastes all together, and makes a movie. Making all the parts good is not the same thing as making a good movie. They are just making some good clips and connecting them to make a monotone movie. It could be good for the people who cannot focus on the more complex things. They are easy to understand and people do not want to do the brainwork anymore. What a shame, there are no new movies that as half good as the good old ones. Jane was someone admiring this good stuff. I miss Jane, I should call her some time. When I watch the movie, I fall asleep. In the middle of the night, I hear some mechanic sounds, when I open my eyes a bit, I saw something passed in front of my window. Mechanic sounds said “Ramy Johnson, we are arresting you due to your acts against Freedom of Speech Law and Government Pro-Life Laws. Please open up the door.” I could not understand anything. After approximately ten seconds later an FRPD officer slam opened the door. They grab me from my bed and handcuffed me aggressively. I said “What-what have I done?”, replied, “Sir, you have the right to remain silent, we recommend you that.”. I was shocked could not do anything, I just said “What have I done?”. The Robo-police answered, “Sir, please do not resist the arrest.”. I could not get my thoughts together. I said, “I am not doing anything illegal and I am not resisting, I just need an explanation for this situation.”. The Robo-police start to process and made a notification “The suspect is resisting to the arrest, this is an attempt to prevent the justice system to function, the right act is execution the subject to prevent the malfunction! We will perform the execution to subject by firing each cop three shots at him, are you having any counter argument to the execution.”. I was blundered, I could not have my thoughts off from asking “What I have done?” to myself. In a spark of a moment I said, “So it is an execution with fire squat as the only army force in the country are the police departments and there are more than one firing infantry.”. Robo-police asked me “Yes, well what is your argument?”. I did not know what it will do but I asked to see if there are any chances “Can I use my last cigarette right?”. Robo-police stumbled and said “Well, yes but in our records, we clearly see that you are a non-smoker.”. I said, “Well, I always wanted to try once, so can I get some…”. Robo-police said, “I do not have any smokes by any chance, but if you insist, we might have to go to the police center to give your last smoke and proceed the execution.” I replied, “Certainly, I do.”.

I was going in a police car driven by two Robo-polices. I was afraid and thinking about what I might do wrong, but I guess it was too late to think. I know watching old movies was not seem nice by the government, but it was not illegal too. Either way, now I was charging with malfunctioning the justice system and there is a death penalty on me. Maybe there would be a chance to talk to someone and cancel the death penalty. We were going ahead in a big way with high speed and I was afraid like a little child who runaway home. I stuttered and asked, “Are you going to kill me?”. Robo-polices just laugh and laugh more, the Robo-police in the shotgun seat turned his head to me and prepared to say something, but an error occurred. First, the Robo-police’s face screen twitched and turned into white and neon pink. Then it started to move randomly, there was steam coming from their body and both Robo-polices were frozen too. Slowly, the car started to slow down, I guess the driver was not stepping on the gas pedal anymore. There was a right turn ahead, but the car was going straight. I could not do anything, even the door was not opening. I hold my breath near the crash. All things are blackened, I open my eyes and saw the two Robo-polices was split into two. I slam my head to the driver’s seat due to impact. I tried to open my door, it is opened, but I could not push the door, it was a bit jammed and I was in shock. I saw someone opening my door, a young lady with blonde hair. When she finally opens the door, I saw her face. 
* Oh my god! It was Jane. Jane said “Hey, Ramy did you miss me” and grabbed my hand and pull me outside. I was shocked again. I was sitting on the side of the road and try to make sense. I said, “H-How do you know I’m here?”. She said “Listen when I break up with you, it was not anything with us, it is just something that I cannot tell you that time. I will explain everything, we just need to get away from here before more Robo-dummies come. She holds my hand and we started to run. I was not outside for years and we were outside the city too. Everything was different to me. We see some cops searching for us and the only direction we could go was a narrow street. We enter the street and keep running. A police van appeared behind us and it was coming fast. We were running, but not fast enough to run away from cops. The end of the street was near, but also impossible to reach without run over by the police van. The Police van was not going to slow down, they were not going to arrest us, they want to kill us. The end of the street was two or three steps ahead but still was impossible for us. Within my last move, I pushed Jane hard to the end of the street, but now the police van was running me down. It hit my shin and I fall really hard, I think I just broke my nose, the van was kept crushing my bones. The last hit comes to the back of my head. My skull is split open, the back of my skull snap and burst into the air and my brain was all over the van’s bumper. Everywhere soaked in blood.

I opened my eyes, with fear, I was in my bed, I immediately look at my arms, they were okay. Then I touch the back of my skull, my skull was in one piece, my brain was inside, I was feeling okay. I heard a woman voice; Jane was sitting by my bed. I was surprised and said, “Hello Jane, how all this happened?”. She replied with a formal tone “Mr. Johnson, the test that we had done yesterday shows us that you are completed your sentence and you are ready to come back in our society. We wish you luck in your next chance.” And I said, “Was everything here was fake?”, she replied “In a way yes, but not as you think. All the jobs and tv shows, dinners, movies that you watch was a small reflection of our society.” I was devastated “But, I think we were...” she interrupted “Lovers right, it is a basic misconception often prisoners make. They just want to make a connection with life, with someone and I am the only one that they saw in simulation besides robots. It is basic human anatomy. I will leave you now and let you gather your things, you have two hours to live, at the end of the two hours an officer will come and help with your departure procedure. Have a good day Mr. Johnson.” And she left.

I just do not know what to do now…

