# Privacy Concerns
by _Başak Göksel_

In 2070, technology is not the same as in 2020, but it was not that different. The screens we used in 2020 were still in our lives, but they were much thinner. After the crisis last year, people were afraid to live. In the past, there was nobody left who could look at those screens we loved so much for more than 15 seconds. Everyone in the world started to communicate with letters as if they were back in the past. With a total of 3 postmen left in the country - which is just for show - the most popular profession was postal business. I can hear what voices of the crisis that occurred last year. Although the crisis broke out last year, it has accumulated since 2032, but nobody knew about it. To summarize the incident, we have known for a long time that brands are listening to us over phones. But nobody was disturbed by this. As a result, what was artificial intelligence was the one who listened to us, what we were talking about as if it was important, they were listening and what was happening next, and it offered us an advertisement about it. When this is the case, the subject was closed when he did not care about the events in people. A new technology entered our lives in 2032. Small chip-like tools were placed under the skin of people with this technology. This chip-enabled us to project the phones we hold tangibly in our hands onto a surface or directly to the air as a projection. When the technology first came out, everyone was shocked. Because it did not enter our lives gradually like other technologies. For example, people did not get into electric cars directly. Hybrid vehicles were used first, then electric vehicles started to be used gradually and the environment reacted accordingly. But when this technology was launched, it was so affordable that there was nobody left who didn't use it. Using this technology in 2032 was equivalent to 4 breadcrumbs. Very suitable. We should have understood at that time that there was something wrong with this. However, we continued to use technology with pleasure for years to flow like water. Until 2057. This chip technology we used was supposed to constantly check people's health information and identify and warn possible diseases 1 week before. In 2057, most of the world's population consisted of elderly people. Coincidentally, most of the elderly, especially those over the age of 75, suddenly had a heart attack every day and hour. But since this is not news, people hear people who have a heart attack around them, but they did not know enough to spread it to the general, so they continued to give people their ages. I did that too. In 2065, the world population suddenly started to get younger. The old people died, yes, but the young people suddenly started to multiply. Even my friends who said that I never want children, the most important thing in my life is my career, had three or four children each. Everyone in the world was very productive and efficient. We were robots, but we didn't know. The years passed like this. A few people suspected what happened and tried to raise awareness, but no one believed them even once. They were in the same position as someone who says the world is flat in everyone's eyes. As the days passed and months passed, one of these suspects came out and spoke to people with a signal tone. Nobody understood what was happening, but everything he said made perfect sense. Because the sound of its signal deactivated the chips in our bodies for a while. He told people that they should get rid of the chips on their skin immediately. A few people with the courage immediately cut off their skins at home and removed their chips. Thus, the process of people's fear of technology started. People can be controlled, even sick and cured, thanks to these chips. We couldn't believe it. We lived in a huge lie. Who killed our loved ones? The brand that introduced this technology to the market… Nobody was using the chips 2 months after these events happened. In this process, states took control and the processes of individuals getting rid of these chips were planned and they managed this process until there was no one left with a chip. Brand owners were sentenced to life imprisonment. But who would this punishment benefit? People stopped their phones and couldn't look at their televisions Those productive fertile people started living like plants. Because it was their success or what they did with the chip? People who could not find the answers to the questions started to get psychologically ill. Antidepressants have become unavailable. The world started to live like it was in the first ages. There was internet only in government offices and those who needed it could go and use it with an observer.

The effects of the crisis started to wane towards the end of the 2080s. People were a little more comfortable using Technology, but it was never the same. This situation affected natural states in every way. Most states have come to a tipping point. Later, all states gathered and planned how they could make people use technology. At this point where there is no trust in brands, returning was almost impossible for at least 10 years. In the states, they planned to change brands from private to state institutions. Since they cannot act according to their minds when they have a state at their head, individuals looked at this situation warmly. And all files of state institutions would be made public. Individuals would be able to access information stored about themselves and delete data they did not want. Although this solution doesn't sound very logical, the public liked it very much. Because the information these brands kept about them was disclosed to the people beforehand. People who read even the finest details about themselves allowed them to keep the information as they did in 2020. From being private to state institutions, brands gradually gained the trust of people for 20 years and gradually continued to privatize.

Nowadays, people are not afraid of technology as much as before, but they did not put them under their pillows as in the early days. But as time passed, people forgot what they had experienced, and people who had to go through this painful process got older. Including me. Now young people live with technology as in our early days. No matter how much it was told, because they didn't experience that fear, they could not grasp its seriousness. I don't know how it will be 30 years from now, but the situation does not look very bright. I hope the young people are careful and don't make the mistakes we made.
