--- 
title: "Growth & Decay - Privacy Concerns"
author: "Bengisu Çelik"
---

# Growth & Decay - Privacy Concerns
by _Bengisu Çelik_

The year is 2040. Those who assumed that the capitalist system that had been going on for years would end were wrong. This system became stronger and the only power that could not be cut off. Covid-19, an epidemic of upper respiratory transmission that took over the world 20 years ago, was expected to keep everyone away from consumption and limit their socialization. But that's not the case. The Simple Life established at the beginning of the epidemic, celebrating the return of nature to itself, was a completely imaginary dimension.The system has renewed itself as much as it ever expected, and people have not given up on consumption. For this reason, the idea that capitalism had reached its saturation point was completely superstitious. The epidemic lasted for many years, suffering from various mutations.Humanity has dealt with various genetic diseases. Mental retardation was observed, especially in undeveloped countries and the elderly population was wiped out from the world. Generations hungry for consumption for years have left themselves in the arms of consumption, which they have blessed in the name of freedom.When the system reached its highest saturation, the existence of the state was now just a formality.

Big tech companies have once again realized how weak manpower is in the epidemic and have focusedof robots by eliminating manpower. That's why the economy was on the side of the strong. People were more and more faced with hunger and drought.The gap between classes, dating back 20 years, was now at its sharpest.He committed various crimes to maintain a lower-class life. Because of the water, people killed each other. Big companies have established dominance over people by using this situation as an excuse. Such great developments had been made in this direction that robots, the militar power of companies, responded to every resistance provided by states, especially those who refused to adapt to the new world order. Robots knew people by codes, and people didn't have identities. People had lost the concept of family. They didn't have names. 

These robots were also owned by BostonDynamics, the company that had the most say in the world. BostonDynamics, an artificial intelligence and robotics design company, was founded in 1992 by Marc Raibert, a fellow of the American National Academy of Engineering, and other colleagues. Now the company is using States as intermediaries to carry out its plans and implementing what it has designed for the world without difficulty. The state went to food, electricity, water restrictions with the guidelines it received from the company. In addition, several other companies existed, and these companies used the underclass, which was ignored in the world, to add strength to their strength. Just as animal experiments were conducted for humanity in previous years, now the lower classes were subjected to experiments to further enrich the upper class. As those who succumbed to the epidemic, these segments lived outside the areas dictated by companies.There were no names of people here, and there were no names of days. The lower class was only allowed 6 hours of Sunday leave. It was also called Bostour. A combination of BostonDynamics and hour. Other days meant nothing to the lower class. In the same way, the seasons had disappeared due to global warming. Children living in great luxury in the powerful chain of the capitalist system, their robots told the seasons as if they were telling tales. Also most animal species no longer existed.

And the living spaces of those who held power were a completely different world. It was so fascinating that the lower class couldn't even dream of it. BostonDynamics branches allocated to our country by the United States took over places such as Istanbul, Izmir, Antalya. The winners of the system lived here in excellent city regulations and prosperity. Robots made the biggest contribution to this. Robots for all ages and identities were available. They were totally helping people. There was no transportation problem. Health problems were quickly solved thanks to medical robots. But for those outside the system, the situation was different. The robots were cruel to them. In experiments required by companies, these people were brought to the centers by robots.

For companies, robots could track these people's emotions and control their private lives. A separate unit called Robotic Sense Tracking and Response Team was created for these robots. Even if they acknowledged the cruelty of this, there was no other solution for this poor segment. They were bowing to the top. Otherwise, bad urban areas, the lack of hygiene of these areas were leading them to death. They were in need of help from the upper class. Exile was applied to the communities that made an attempt upon the re-strengthening of the state. People in exile were sent to places where drought prevailed, where earth resources were depleted, called the Emergency Traditional Fossil Fuel Accumulation Area.

When the stars of robot design companies did not shine so much, Microsoft complained of losing its throne, making itself known and once the richest in the world. He did not accept that such ruthless companies separated humanity with sharp boundaries. He was aware of the crimes against humanity and developed new software because he knew he could not defeat his opponents alone. He did this by first disabling robots responsible for sending people to be sent for exile, and training this audience under his own brand. It later blocked Bostondynamics' robots from accessing information that violated the privacy of lower classes. In this way, while the communities that made more revolts were sent for exile, they were actually fighters for Microsoft. In this way, Microsoft has at least managed to restrain the companies that are making the world cruel.
