---
title: "Landlessness"
author: "Caner Türkmen"
---

# Landlessness
by _Caner Türkmen_

**Abstract** 

> _The natural balance of our world has been turned upside down. Natural disasters continued for years and all continents in the world except America were either shattered or swallowed by the oceans. A small number of people who have managed to survive in the world struggle to survive in the American continent._

The shelter, built to withstand all kinds of disasters, seemed to have worked. He had been lying left and right like a boat in the endless ocean for months. The supplies he thought would last for an estimated 6 months had decreased, indicating he had been in the shelter for more than 4 months. Again on such a day, he felt a strangeness, and he was hearing waves. The great excitement in him, this time when he put his head on the sunroof, he didn't want to see the ocean like a desert again. This time he wanted to see a piece of land. An amazing thing, if his ears were not playing tricks on him, he could hear human voices. He was afraid to leave his haven. People could be dangerous to him.

Imagine you are reading a novel, and the book begins like the paragraph above. You would probably think that someone survived the post-tsunami shelter, or that the sinking ship traveled in the ocean for 4-5 months with its specially made shelter and hit the shore of a region you thought was a primitive community. Or doomsday scenarios consist of phenomena such as thirst and meteorites. But I'm sure very few people would think the cause of this incident would be landlessness. I am also in that minority. For me, the end of the world will come from landlessness before thirst. Here, our hero was the conscious inhabitant of the land that was submerged months ago. Thousands of earthquakes have occurred in the world in recent years and these earthquakes have caused incredible destruction. Many continents are lost in the split oceans. All continents except Asia, Europe, Africa, and America are at the bottom of the ocean. Rising waters have absorbed a large part of the American continent. Earthquakes and streams of natural disasters devoured the mainland. Most of the people died. The lucky people who threw themselves into the American continent had to deal with insufficient resources. The world where the great utopia has been realized has been dominated by a single state. People also have no discrimination of religion, language, and race. Due to insufficient food and technology, people had to revert to primitive methods. It was understood that land was more important than money, and the state took control of the land just like money. The materials that could survive the occasional wreckage were worth wealth. Even though the vast majority of people perished, a considerable population was trapped in the American continent. People were settled all over the continent in a planned way. Thousands of immunocompromised people were dying here too. The crime rates had increased enormously and the state had become unable to control it. Criminals were sent to Alaska and left to die there. Those who were American citizens, whose personal and national interests prevailed here too, accepted that they were superior. They claimed that they should have a single voice in management. When these differences of thought caused conflicts in places, combined with the insufficient resource shortage, reactions and tendencies of violence grew and interventions became harder. All states in the American continent decided to unite and their center became Washington DC, the current capital of the USA. Each nation tended to colonize itself. Realizing this, the government made a planned distribution process and placed groups of different races in each region. Agriculture was completely under state control. Resource usage caused great controversy. Conflicts have already erupted in the south of the continent. People could not move even interstate without special passports and reason. Health and education were almost over. State authorities, who did not doubt that these conflicts would spread throughout the continent, found the measures to be more aggressive. The man continued to eat each other here as well. He used unimaginable resources to build weapons. The state is arming for the rebels, the rebels for the state. In such an environment, people had to live. Almost all electronic devices do not work. Satellite and wireless communications were over. People had difficulty even accessing electricity. Natural disasters for years have also affected the Americas. Everything turned upside down, and those that remained intact did not work properly. The state had virtually no technological material left. People exchanged by barter method. Mechanical tools for humans were worth more than silver, money, or even gold. The number of people looking for materials to explore and barter along the coast was enormous. The state could not find civil servants to employ. Because nobody cares about money. Only the state and people chosen by the state could produce a new product. Since resources were limited, the state wanted to control resource use. 

In addition to all these, information was needed to improve the technology. Most of these sources of information had disappeared. The number of scientists was very small. State officials were still intending to search for a piece of land that had survived. The ships that remained in the hands of a few surviving states rotted from neglect, almost all of them became unusable. Natural disasters around the world left neither opportunities nor resources to care for them. As most of the natural disasters took place in the seas, marine vehicles were damaged the most. Government officials estimate that islands, large and small, may have survived in the most remote corners of the ocean. He wanted to reach them. To reach those islands, he was working on a ship project that could cross the oceans. This was a huge gamble. Most of the scarce resources and workforce would be spent on this project. The state aimed to employ criminals in projects for the shipyard and the state to provide labor. Not all was well for the people. Gangs that seized people's valuables had sprung up. They plan to own every valuable item during the exchange. They even used these materials to make weapons. Some groups were plunging into nearby areas that used to be living and now sunken in search of valuable items. The population was increasing steadily. But the only surviving continent was hardly enough for this population because living in a large part of the continent was almost impossible due to drought and desertification. People could no longer fit ashore. Water resources were almost nonexistent. The makeshift machines could not purify the seawater, people were getting sick and dying because of these water sources that could not be fully treated. Some of the scientists viewed this project as a waste of time and resources. He believed that instead of this project, it would be more logical to rehabilitate the deserts that cover almost the entire land. But the state did not take this into account. He was trying to reach the resources that would help technological development as soon as possible and return to the old days. People had a hard time finding food. There were a small number of living things that could adapt to the earth. Fortunately, although the fish population increased due to the lack of hunting, there were almost no tools and equipment to hunt them. Primitive fishing was done and sailing in makeshift boats. Although certain fish could keep up with this new world, it was not easy to hunt them. Fishermen were already going to take a great danger and go hunting. Gangs could easily kill people for fish. The state was having a hard time fighting the gangs. He could hardly prevent them. The state had already focused on the large ship project rather than preventing the turmoil. An act that is considered a crime in our daily life seemed like a normal act for those people. Social life had changed almost completely. It was not expected that people would attach importance to social life as the struggle for survival reached this point. 20 years from now, a newly born baby will not know what the object that hits the shore and what it does and will find the old world from a few pictures or some decaying books. Will things like books or pictures be so valuable that they can reach them? I guess, no. He would remember the old world only with the information that spread through word of mouth. Unless they were killed by gangs or lost his struggle to survive.
