---
title: "Message from Future to Future"
author: "Emre Taştan"
---
# Message from Future to Future
by _Emre Taştan_

The YEAR 2040 ...

I'm 100 years old today. Considering that the average age of death is 120, I have 20 years left. I've seen many eras since 1940. I've experienced them all. Before I died, I wanted to convey this change to 2060. There are big differences between the periods when I was born when I turned 50 and when I turned 100… Technology has changed people in every field. Some of these are;

Small-scale personalized production is dominant rather than mass production.

Physical brands have largely lost their importance ...

There is a race to grab space for hologram advertising in the sky ...

Ads are everywhere thanks to digital lenses. These lenses record everything we look at and advertise things we might be related to by matching.

High school goes on and on. Let's get into the details.

Technology is a phenomenon that develops, changes, and renews people. Although technology and people were out of step in some areas, this offered them new development opportunities. For example, with the help of technology and robots, humans have largely been out of action for jobs that require physical strength or analytical intelligence. Because robots and new devices can do these tasks hundreds and times faster and more accurately than humans. At this point, people become inefficient. But this leads people to orient themselves in new areas and acquire new skills. Because the definition of JOB has changed.

BUSINESS = CREATIVITY

Technology and things that robots cannot or can only partially do - that is, creative work - have become people's new focus. The symbol of success and being equipped is now "creativity". People who can bring their creativity to the forefront in their work are becoming more sought after.

Of course, creativity is not the only thing needed. Another important factor is specialization. To be able to do more professional work and to solve the unemployment problem, even for small jobs, specialization was made. So people don't go to the same person for the digital lens and the digital ring they have problems with. He goes separately to the digital lens specialist for the digital lens and the digital ring specialist for the digital ring. This approach promotes development as it leads people to specialize in specific fields. Besides, it prevents unemployment that can be brought by the increasing population with a wide range of jobs.

The change in the job description and the increasing importance of creativity and expertise also affected the education provided in schools.

In a world where technology and creativity are the main elements, the education given in schools has focused on specialization, technology, and creativity to meet the needs and provide the necessary human development. People receive training in very specific fields, develop themselves on creativity, learn techniques to use in business life, and meet their daily needs. Individuals who cannot use technology are not considered to be in this world.

Another important point in education is; training takes place in a physical environment. Although the school focuses on skills such as creativity and specialization, it has a very important output: Social skill.

The fact that people have strong ties with technology causes this technology to create a world within the person and to be isolated from people. For this reason, people's relationships with other people have weakened so much, and he forgot to communicate with each other "like a human". With the agreements made between governments under the leadership of Harvard, schools have been transformed from virtual environment to physical environment, considering that it is a suitable environment for people to develop these skills.

Many objects have emerged that people have to carry in their daily life. People have more than 10 internet-connected devices. These devices are not a pleasure, but a part of people's lives. All of them are elements that improve and facilitate people's lives.

Digital lenses, the most widely used wearable technology product by humans. With the increase in vision problems due to technology, Google came to the rescue of people and introduced "Digital Lenses" to people. These lenses have a clearer vision than a normal human eye, as well as a device that can be connected to the internet. This is the most important point. Since the device is connected to the internet, everything we can do over the internet is right in front of our eyes; calls, messages, even people's information.

Many brands have produced software for these lenses. The most effective of these was Facebook. Thanks to the software that Facebook makes to the digital lens, the profile of the desired person can be seen when looking at that person. Thus, the desired person can be contacted easily. We no longer need to go ask or search for hours to find out someone's name, age, or profession. The only thing to do is to look at the person whose information we want to learn and access their information.

Also, "Electrıcfoxy", which has taken the opportunity of many people to use digital lenses, started to produce digital clothes suitable for these lenses. Thanks to the chip placed on the body, the person can easily catch the fashion without effort. You load the purchased clothing models into the chip and wear them whenever you want and change them whenever you want. Thanks to its personalization, its size, size, and color are made as desired. Now we can say that fashion is at our fingertips.

Technology and these devices have helped people have more say about their health. So it is more dominant on people's health. Thanks to the "Digital Ring" produced by Apple, it displays harmful cells, muscles, tissues, tendons as well as simple measurements such as sugar and blood pressure. All you have to do is hold it over the desired area and look at the results from the hologram.

Besides, the ring can be used not only for health purposes but also for communication. Thanks to the hologram image, it includes operations such as speaking, searching by voice command, and navigating. Thus, a small tool has increased people's control over themselves and made it easier for them to communicate.

With the increase of robots, people's sports habits have also changed. Robots specific to each branch are now available. People buy these robots, customize them, train them, and put them into competitions. For example, consider a boxing match. Robots come into the ring. Each robot has sensors attached to the robot on its owner. Thanks to these sensors, whatever movement the owner of the robot makes, the robot instantly makes this movement. Thus, robots fight through their owners. Of course, this applies to other branches as well. In athletics, robots own effort, but the runners are robots.

Even sports have changed, but the subject of food has not. Eating is a pleasure for humans. One of those rare things they won't give up. For this reason, the subject of food is the same as in the past. But there have been changes in the way of production. In order not to accelerate the bad course of nature, the animals (especially meat-producing) were extinct. Under the leadership of Impossible Foods, meat production in the laboratory has reached 100%. It's not just meat. Many products are produced in the laboratory. Cheaper, more nutritious, tastier, and more environmentally friendly.

The increase in the human population and the filling of the lands made transportation difficult by large vehicles. For this reason, electric autonomous bicycles have gained value and have even been made mandatory in many places. With the autonomous electric bike made by Xiaomi, people have entered a comfortable, fast, and space-free era in transportation. These bicycles, which are quite fast, are compatible with smart roads, take up little space and have a zero accident rate.

Finally, I want to list a few more things like at the beginning;

People are very lonely in their daily life. Because they have a virtual universe of their own. For this reason, they spend most of their time at home. Thanks to enhanced technology and wearable technology, she enters the virtual world - games - and engages in activities, and lives in the world she fictionalizes and desires.

Many small things it needs can be easily produced in seconds with the 3D printer in their home.

People are not cleaned with water. The approaching water shortage kept people away from cleaning with water. Brands led by Unilever have introduced shampoo and cleaning products that do not need water.

I hope all this 2040 information will move to the year 2060 and let them know about their past.
