---
title: "Tap to Reset"
author: "Fırat Duğan"
---
# Tap to Reset
by _Fırat Duğan_

**Abstract** 

> _Jason L. is a cyber-detective. His mission is the catching the cyberbullies. However, Jason got a case one day. The man whose name is ‘There_is_no one’ is in the police department and, he had some information about a big cyberbully._

**Everything Started with a Coffee**

Jason L. was a outstanding cyber-detective. He was not a big person that all. He didn't have big biceps but, he was really good to use computers and cyber systems. He hacked Google servers in 12.5 minutes during his junior years at the police college. He was nearly kicked at the school but, the professors didn't allow him to. After his graduation, he got lots of cases and, he got a promotion really fast.

He came to the police department. He tried to remember what he forgot. However, The office chef Melissa called out to him when Jason got to his chair. She had a case file in her hand that was a big title on its top. 

Jason went to Melissa's room and, he closed the door. Melissa looked nervous. ‘What is the problem?’ said Jason. She gave the file to him. Jason's eyes got bigger when he read the title. The title was 'There_Is_No_One'. Jason remembered what he forgot suddenly. ‘I need a coffee!’ he said.

**The Lockdown**

Judy L. Harris was a good citizen and, she was an honest gynecologist at the Millennium Hospital. She paid her taxes, fallowed the rules. There was not even a parking ticket.
 
She woke up and started getting ready. ‘Alexa, play Rossini, please!’ said Judy. She opened her laptop and checked her mailbox. There was an e-mail regarding the new hospital rules. She didn't realize her laptop was hacked by someone when she clicked the mail. The music stopped and protection cages landed on all the windows.’ You are a cyberbully. The police are coming. Stay calm and, wait. You will not be harmed if you cooperate. You are on lockdown.’ said Alexa.
 
**There Is No One**

Jason knew that nickname. That nickname was a sign who belonged to the hacker. ‘Where is he now?’ he said. ‘In the interrogation room.’ Melissa said. Jason tried to go to the interrogation room very fast but, Melissa stopped him. ‘He came to us voluntarily. He wants protection. In return, he will tell us everything she knows.’ Jason was surprised but he didn't show her. Before exiting the door, he turned and said 'So give him to it.'

There was a woman on the chair in the interrogation room. Colored eyes, blue hairs... She was nice. When Jason entered the room she looked at him. ‘Oh! Famous detective Mr. Jason L. How are you today sir?’ she said. Jason sat on the chair and, drank his fresh coffee. He said ‘You already know me. I will not introduce myself but, who are you?’. She leaned forward slightly from her chair and smiled, taped the header on the file twice with her finger. ‘Mr. L. There is no one. You are not talking to somebody right now. I'm an unidentified person. Whatever. The real question is why am I to here?’ Jason didn’t say anything. 'There will be a heist. They will steal people's IDs. Newborn, child, adults... Lots of ID. All the persons who have a file at Millennium Hospital in danger.

‘How do you know that?’ Jason said. The woman sitting in the interrogation chair leaned back and said ‘I wrote the software for stealing the IDs. Stanley Jacobo gave orders.’ Jacob was shocked. ‘Stanley Jacabo? Owner of the Millennium hospital and future presidential candidate? But why?’ he said. ‘Info is the power.’ said her and, continued ‘If you want to catch him you need someone inside the hospital.’. Jason looked her eyes and ask‘Who and, why?’. The woman smiled and said ‘Why? Because someone has to go unnoticed into the ID registration room and insert the flash drive into the computer. That person is Judy L. Harris.  Don't worry I brought her here for you. 
 
Detective Jason entered the room that Judy Harris is held. Doctor Judy looked at him in panic and said ‘I did nothing officer. I swear.’ Jason said her ‘Calm down, Mrs. Harris. Are you a doctor at Millenium hospital?’ Judy nodded in surprise. ‘We need your help.’ said Jason. 

**Co-oparation**

The next day, to begin her work, Doctor Harrison got out of her car in the hospital parking lot. She passed security, smiled at her colleagues. After getting on the elevator she heard a voice inside her ear. ‘Nice! Stay calm and keep moving.’ said Jason. Doctor Harrison said ‘Ok!’ and, after getting off the elevator, she headed straight for the registration room. When she was going to have the pass card read, someone called her.

‘Mrs. Harris! I am looking for you. We need to talk. Let’s get my room.’ said the manager Lawking. She walked with him to the room. She was nervous. The manager asked ‘How was your yesterday Mrs. Harrison?'. ‘After hard work, some vacation was good.’ she said. Judy heard Jason's sound in her ear again and he said ‘The manager is suspecting something. Tell him a lie.’. Doctor Judy continued ‘I watched film and got rest.’. 

The manager was not interested in what she said. He took a sheet of paper from her desk drawer and held it toward her. ‘Here's everything you need to quit your job, Mrs. Harris. You can tidy up your table. Thank you for your services.’ he said. Judy shocked. ‘Sorry. What?’ she said. 'You've been fired. You can out. Thank you.' said the manager in a cold voice. 
 
Jason and Melissa looked at each other in the secret trailer outside. Judy desperately left the hospital and walked towards her car. 'The whole mission has been ruined, what do we do now?' Melissa said. When Jason turned to reply to Melissa, a black panel van appeared on hidden cameras. The van went near to Judy's car and the back doors openned. Two men caught Judy and took the van and dissapered. It was too late when Jason and Melissa realize that.

**Back to the Batcave**

Jason burst into the interrogation room. He shouted 'What have you done? You know they are watching.' The hacker said 'Yes, I know. Because of that, I gave you the flash disc. It was a GPS. I can find where she is and, I can shot down the software before the heist. Jason was angry. He said ‘I don’t trust you!’ She said 'You don't have another chance. I need my computer.' Jason thought and ‘We can arrange a computer for you.’ She said ‘ No, I need my computer.’
 
After Jason set the required permissions, they went to the house of the hacker with Melissa. That house was a regular apartment. There was not an extreme thing. House decorated was relax. There was not too much furniture. When they entered the hacker's working room, they saw a computer desk but there was not a computer case. All the desk was designed with computer parts. Jason looked and said 'Oh! Fascinating. Do you steal IDs on this computer, don't you?’ The hacker just looked at him and smiled.
 
After a half-hour, she said 'I found her.'  Jason said 'OK! I will call for support. The hacker said ‘Calm down, boss! She is on the depot where the server has the software. If we are caught by them they kill all the clues and girl.’ 'Can you shut the server down?' said Jason. ‘Yes but, I need to access the server manually.’ the hacker said. Jason looked at Melissa and, Melissa call the her assistant. 

**Who Are You?**

Judy was scared so much. Who were these guys and, why they chose her? Then, she heard a man's voice. She knew that but, she couldn't remember. Who was him? They pulled out the sack on her head. She saw the manager Lawking at the Millenium Hospital. The manager said 'How was your day Mrs. Harris.' Judy felt like she fell over the cliff. ‘Do you know how are IDs cost on the black market? Why everyone should has just one account on the pc? It's sucks. I give them their freedoms. I will burn this shit system. I will burn this shit system. After that, I will say Stanley Jacobo did everything. I will be rich. Jacobo defends this system because he wants to be a president. I worked at that hospital for years. What did he do for me? Nothing. I will burn him too.’ 

To the outside, the special forces surrounded the areas. Everyone was ready for the order. Then Jason said 'Now!' on the radio. When the manager Lawking heard the gun voices he started to run to the back door. However, Jason and his team was waiting for him. They caught him in easily. 
 
Jason took the hacker and run to the depot. Judy was tied in a chair and was not moving. She fainted with fear. They untied her and Jason went over the radio for the paramedics to arrive.  Melissa came to them really fast and said to Jason 'Take her and, go to the server. We will be here.’ 

The hacker went to the server with Jason and, she took every clue for cops. Then shut the software down. When Jason took the hard disc that has the evidence he looked at her and asked 'Really! Who are you Mrs. There_is_no_one.’ 

She laughed and said ' I am the hacker and also I am the daughter of the owner of the Millennium hospital.’ Jason was shocked. ‘My father and I are not meeting, but I knew he wouldn't do such a thing. my father is trying to prevent people from living what they went through before the great cyber-war. I support him and this system.’ Jason was shocked again. He started to laugh and said ' You are a hacker and you support this system?' She said ‘Yes and I am an detective too. I'm Melissa's mole inside. We have been conducting the operation in secret for years. That's why you've seen my name in so many places.’ Jason looked her and said ‘Your nickname!’. The hacker said ‘Oh, yes. By the way I am Sarah. Sarah Jacobo.’ 

**Everything Is Fine**

After the operation Jason, Sarah and Melissa went to the hospital that Judy was being treated. She was fine. When they were talking to each other  Stanley Jocobo is came to the room. He said 'Hi! I hope you are fine.’ Judy was not expecting to see him. 'Yes, I am. Thank you for your visiting.' she said. 'Oh! Don't thank me. If our professional cyber-cops didn't catch them they could do many worst things. Moreover, it is my duty to visit the new director of my hospital.’ he said.

Judy was frozen. ‘Th… Thank you!’ she could say. ‘I hope you will be fine as possible as fast. We need you.’ he said and he smiled her. He turned to Sarah just as he was going out, and said ‘Maybe you'll come to dinner on the weekend. Your mom will cook your favorite food.’ Everyone looked at the Sarah. She could not hide her smile and shook her head positively.

After telling Judy to get well soon, Melissa left them. Jason couldn't stand and asked Sarah ‘Why you don’t talk with your father?’ She looked him and said ‘I will tell but, I need to eat something.’ Jason looked her and said ‘Yeah! I need coffee too.’
