---
title: "The Crow"
author: "Hakan Hanay"
---
# The Crow
by _Hakan Hanay_

**Abstract** 

> _After the migration, earthlings were busy with the Techno Helmets in Alpha Centauri._

When humanity completed its migration to Alpha Centauri, they said goodbye to each other and settled in the one-room, high-rise buildings called Technopolis. Technopolises were areas designed only for one person, where the control was easy and people could not communicate with each other. Centaurians were able to get food and drink from vending machines only on certain days. This process was monitored by drones and inspections continued until there was not a single person left outside. These inspections were to maintain order and prevent a possible threat. In any case, no other situation that would contradict this order was observed. For years, people have been living the lives they wish and idealize with their techno helmets in Alpha Centauri. Every moment they took off the techno helmet was meaningless to them, each one was busy with living their life through another ideal. Alpha Centauri was a dream place for every earthling who gets tired and bored while chasing the ideal life.

In the early days, everything was as it should have been, and there was no out of order behaviour. Earthlings quickly adapted to techno helmet technology and completely cut off their communication with each other. But after a while, the confused earthlings used this technology to live their old lives, not the ideal. It was always a voice in their head, ideal for Earthlings. Therefore, they were practicing the ideal for the first time and did not find this practice sincere. They wanted to return to Earth, but it was too late now. They put on their techno helmets and went to visit their friends, had picnics, walked, made love, tried everything to taste what they used to have, but they always felt insincerity and coldness. They thought that the ideal was nothing but fiction, and like the techno helmets in their heads, they believed that the ideal was an imposition. They also believed that every blessed act made a person insincere and isolated from life. Over time, they had begun to completely lose their relationship with objects and their ability to empathize.

One day, one of them went out of order, turned to the person behind him in the vending machine, and told him that a crow was coming on the window of his room at night. Her eyes were full as she spoke. She hadn't spoken to anyone since the day he set foot on Alpha Centauri. When everyone dispersed, she opened the door and waited. Before long, her friend had come to visit. Together they went to the front of the window and waited for the crow's arrival, and during this waiting, they talked at length. They hugged each other with the happiness of sharing the same feelings. After the long wait, the crow came to the window. They took the crow into the room and observed it for a while, and they were captivated as if they had never seen a crow before in their lives, they wanted to share and show this feeling with all earthlings. This crow was the only real thing they had, they didn't want to break with him, and the riots began exactly that day after. Everyone who heard the crow wanted to see it by secret visits. When the Earthlings saw the crow, all the pessimistic feelings that they could not understand were wiping away for a moment. They believed that what they felt was the same, even though they had trouble conveying what happened to each other. They wanted to escape, they wanted to return to the world, love, and be loved. 

Earthlings did not act selfishly and wanted to show the crow to the Centaurians. But some brave Centaurians who agreed to see the crow did not share the same feelings as earthlings. They said it was just an ordinary crow and it didn't evoke any emotion in them.

Earthlings, with the relief that came with the crow, were now completely out of order, spending time with each other and did not need techno helmets. This posed a threat to those in control, the fact that the earthlings acted outside of the lifestyle that had been going on for years made both the Centaurians and the inspectors nervous, and they took some of them on trains as a display of force and sent them to prisons 100 thousand kilometers from the Technopolises. However, this intimidation made the earthlings even angrier and they displayed behaviors aimed at destroying everywhere they were and disturbing the peace.

The supervisors, angered by not being able to identify the problems that this migration could cause, decided to lock the earthlings in prison and leave them to die. But in doing so, they also hid from each other a strange feeling they had never felt before. They put the techno helmets on their heads, wiped out all earthlings from Alpha Centauri, and for a while convinced themselves that this was a right decision.

After the mass destruction, Alpha Centauri left no trace of earthlings and the crow, but all the Centaurites opened their eyes with a feeling that they were alien. They couldn't wipe the crow out of their brains. Where is he now? Is he happy? They were thinking…
