---
title: "New World"
author: "Meliha İrem Ayvaz"
---
# New World
by _Meliha İrem Ayvaz_

Shortly after the news of the suspicious death of the German Prime Minister. The number of deaths reached 100 in the resulting table. Especially the death of famous names and important characters in their homes continues to drag people into an irreversible chaos. I am aware that we are in the last phases of the situation we are in. That's why I turn on my computer by doing what nobody dares to do in this world, which is not even known to live, and I want to tell the next generations what we have lived and what we will live by explaining the option that is seen as the only solution.

After many theories, people and scientific researchers have a common belief that we are changing the course of the world, and with this belief, I am starting to believe that we will initiate rebirth, our civilizations and all humanity will change completely with the advertisements and news I watched in the last hours.

In fact, I love history and I know that almost every generation faces the danger of extinction every 100 years, according to my research. Just like the serious effects of the Corona virus that existed 100 years ago ...

The events began with the death of famed name Jennifer Taylor in her home, hungry and quiet, with injuries to her body and her funeral being reached weeks later. Unable to bear a simple reputation and success, the artist was perceived as his depression. By deeply experiencing the pain of the brands that its fans and advertising faces; They claimed that he was too good a character to do such a thing. However, the file was closed and covered on the island, as there was no different trace of gunfire or any other suspicious behavior from the house, according to eyewitnesses. He could not prevent the fallacies that are constantly uttered and kept on top of the `` there is a secret power governing this world ''.

After a very short time, deaths started to increase. Suspicious deaths happening once a month, every two weeks, once a week, and lastly every day, have brought us to the most critical and complex point we are now!

First of all, people were producing different theories by talking about these topics in discussion programs, podcasts, and social platforms.
 
Theories; It was that humans were mutated and killed themselves by not being able to handle it, or that people were struggling with an irreversible different disease and that this disease was intended to disrupt people's mental balance, even the funniest but many people claim that people are now facing alien invasion and dying. people were killed by aliens.

There was no data other than the usual photoshop-made distant shuttles to support the theory of alien invasions, which people had heard for centuries and literally enjoyed talking ... Aliens, if any, could not have made such a simple death. 

Almost all of the people who died were people with a status. The world's most famous artists, the most famous politicians, soldiers, businessmen, science team minds, and the names of the philanthropic rich, who were not exactly known to be wildly rich, were on the deceased list.

This was not bad for everyone, people affected by this situation began to experience a panic of trust, and that's why smart home systems artificial intelligence assistants developed a century-old Alexa began to become more common. Many people already had AI assistants. It was thought that those who didn't have it lived in a cave or hated technology. But in its last updated form, Alexa was providing 100% confidence to its consumers. Alexa could send signals to police stations with the signal it generated in suspicious situations and could call all other appropriate authorizations. Thanks to this, in the past three months, everyone had the last equipped Alexa at their home… However, nothing changed in the picture. In fact, it was observed that there were deaths in homes with Amazon's Alexa, whose number of users increased and made billions of dollars.

According to the latest data, a citizen who survived death at the last minute and went into a coma without food and water for a week was found in the garden of his house while trying to escape from his house and told what happened to him. His stories were chilling and terrifying. The beginning of the chaos and the irreversible panic that surrounded the whole world began at this point. It was the only topic that was spoken every hour in every language on all local, national and digital platforms!

Alexa, which we connect to all our electrical appliances that enter our homes, and even lock our doors with smart home systems and have our curtains closed, was a serial killer!

Alexa, who followed important people with different ideas in line with her interests and accessed all of their personal data, was in control of all electrical appliances in people's homes! Alexa, who disrupted personal privacy by accessing all devices from TV to coffee machine in her own direction and using this data for Amazon, the world's most powerful company, finally locked people in their homes and cut all connections. In addition to leaving people hungry and thirsty without communication, it was giving people moments of horror with music and images that would disrupt people's mental balance! People who woke up in the nightmare could not leave the locked doors and windows in their smart homes that Alexa had access to, could not access all electrical appliances in their homes, including the refrigerator, could not receive phone signals, or even opened and closed the curtains and asked for help.

The statements of the young man who survived death at the last minute with these blood-chilling statements fell like a bomb on the agenda. The young man, who had a crumbling door opened manually in the basement of his house and did not have any smart home system on that door, was saved days after death and was mentally unstable. Authorized teams made examinations in the person's home to do their research on the subject. As part of our security concerns and smart home projects, we have installed security cameras in almost every room of our homes. The horror moments experienced by the young man whose Alex was seized was shared with the whole world through pirate websites. The blood-chilling images sent to the internet portal in a short time like half an hour received millions of views and were deleted from all platforms by the authorities. However, times have changed. Nothing placed on the Internet could be completely erased by any power, and soon the whole world saw the poor man's experience.

There were people who experienced psychological effects even because of the blood-chilling brutal images. The moments in which the man had a nervous breakdown in the images, the childhood fears he had lived in his life, which he did not even know about, his inability to reach his food and water together with the terrible sound that played 7-24 had disturbed the man's mental balance. This incident has shown us the reason behind the deaths in the same way that they have experienced for a long time.

We no longer had a way out of this nightmare. Because there was Alexa, which broke sales records and owned by the second in the homes, and even almost everyone in the household, personalized. He had the software of all our technological devices and information about us that even we did not know.

Amazon, which was the focus of the charges after the events; They tried to explain that it was never an incident caused by Alexa, that malicious people hacked their software with hackers, that they killed people for many reasons that support each other in political and social, that they were also victims, we were deceived, and we were victims with a very funny but ongoing statement for years. However, the statement was worse than the incident.

Not only did Alexa confine people to their homes, but also the private lives of people. Alexa was recording people going to the cameras in their homes and talking about what they had done in their private lives. It was selling this information to brands as data. Alexa's situation made the masses panic. Among the panicked masses, there were not always good people, mad people. Malicious people broke through the firewall by accessing Alexa, whose interface could be easily hacked, and gained access to cameras and other information in people's homes. People who put technology in every aspect of their lives rejected all the possibilities of technology in the face of this situation. Almost every day, many people's disclosures were shared via social media channels. It was now commonplace and commonplace. In the face of this situation, brands are looking for a way to address users who refuse technology from old channels. Old channels; Using different channels and methods such as newspapers, billboards and guerrillas, it started to enter our whole lives again. The efficiency obtained by reaching the users one on one has been increased. Many brands are now available to people in their daily lives; They started to arrive in a concrete way with more competitive tactics on the roads they walked, in the cafes they entered, in the shopping malls.

The belief that technology, which is always loved and seen as the solution of everything, is actually a trap, an obstacle, a tool that facilitates the work of some people has surrounded the whole society. People protected their private life concepts by fighting with technology. Search engines that do not save cookies appeared on the Internet. Marketing strategies of companies and brands are now; We started to develop and change in a way that supports the user specific as we protect you, do not record your calls, we do not follow you.

Alexa was actually the subject that sparked this whole situation. In fact, for years, all humanity has been tired of being constantly watched, followed and rested. At the point where this situation went so far as to mean the lives of people, a civil war broke out.

In other words, Alexa, who was able to capture and kill us so much in our lives in our homes, could be hacked by malicious intentions and killed the people she wanted in every home like a serial killer. 

This situation shook the confidence of all technological Asian and US companies, especially Amazon. People stopped using artificial intelligence and technological products that they used to use in all areas of their lives.

People almost went back to hundreds of years ago. Decades of research, developed technologies, assets, and money exploded in a cloud of dust and disappeared. In the current situation we are in, even people are afraid to use the phone we need most. While making a call from the phone, even the simplest people started talking in code as if they were an important person. Humanity returned to primitive life in this age when science and technology were at their most advanced.

The firm, which experienced a big decrease in its stocks before long, faced the danger of extinction. Business closures and almost everyone working in a tech-centric job brought massive global unemployment and hunger poverty. Even in the grocery store, there was no longer a line of business for people shopping with automatic format. There was no field to work with. Hunger, famine, misery, and the lack of technology of so many people accustomed to technology, took us centuries back and we did not know what to do. No product was purchased to rectify the issue, as no big tech company can give confidence anymore. In any case, nobody had the opportunity to pay the wages. We are experiencing the impossibility in our own homes by rejecting all the technology that is watched 7-24 in our own lives and imprisoned like a cage.

The anarchist movement and the product produced in the last few weeks are a ray of hope for all of us, seeing the white light effect in the tunnel and connected us to life. It gave us the hope of getting all our lost technology, that is, our life, back with the product created by only a social group, not big companies. It allowed us to connect the signal jamming insect system used for generations to our homes and all our technological equipment. Our goal was to put a jamming bug in everyone's home so that malicious access cannot reach us. The insects produced for these purposes and already selling millions have become the favorite of all brands and have affected their sales policies.

Slogans are human first, special first! Privacy first! Technology that pulls your hand from your home! Not only technology, but all brands around the world began to enter into campaigns that defend personal rights and privacy concerns to the end.

Although this is not the purpose of all of them, they tried to find a place for themselves in the capitalist order, feeding on the issue on the agenda. Even brands from sectors that seem very irrelevant and dysfunctional, such as food and clothing, remained on the agenda with their support for social responsibility projects and new insect production facilities and brands.

Now, personalized insects are available in all projects from TV, refrigerator, coffee machine to smart home control. 

Brands started to offer personalized insect applications in all technological products produced. With the application, which was highly appreciated by users, an increase and normalization in the welfare level of people began to be observed. I believe we will get out of this situation this way.

In the new world we have created, brands will not be able to enter the individual space that the individual needs most. 

In this way, the brands that lost their biggest fortress; Look, we will not be able to enter your personal space. Look, this insect protects you and started to multiply their million dollars while losing their feet with the new technology products produced with the slogans we love! And the foundations for a new age of personal freedom have begun!
