---
title: "Realisation of a New World"
author: "Mualla Bengisu Demirkaya"
---
# Realisation of a New World
by _Mualla Bengisu Demirkaya_

**Abstract** 

> _This is the story of how the world has changed through a virus that has taken all over the world. In this story, we see how the mankind has evolved in order to survive the conditions of a new environment and the new society that has been reinvented with it. We will see how technology can be used to maintain the human life through difficulties._

The year is 2038, it has been almost 20 years since the corona virus pandemic has taken over the world. The virus was first seen in Wuhan, China in the year 2019, this was not the first time that humanity has seen a pandemic but this time things have changed irrevocably. When it first started we still knew what to do; we had options, but one by one corona virus made them impossible. When the year was 2021 a couple of companies developed various vaccines which made all humanity to be hopeful for the cure. Those who could get their hands on any vaccines were relieved without a doubt, of course not everyone in every country has had the privilege to get vaccined. Nonetheless, us thinking vaccines were the solution didn’t last long. Our fight against the virus through the vaccines has failed, it made the virus understand and learn the human kind even better and it made the virus a lot stronger in a way we still don’t understand today. This hopeless defeat made things harder for the world. Lots of people were struggling for sure but hope was the main thing that kept them still going, with the lost of our only hope, those people also gave up on life. By this time, almost 40% of the world’s population over the age 65 were already dead just because of the corona virus itself. With the hopelessness in hand many more people has choose to die, since they thought they had no other choice nor no future. This circumstances made our world’s population much, much younger. It almost felt like a new page, with a new way of thinking and acting. We have already understood that, for a while we won’t be able to find a cure, find a miracle to make this disease to just disappear. So we had to come up with a new strategy, sure we couldn’t win over the virus but since then we have learned to live with it. As humans we have this power to seize the situation and adapt to it, which made it possible to live through this day. The society as we used to know does not exists anymore. People live in cubicle like houses with virtual reality technology which makes it possible for them to have access on anything they can afford, in a way it is just like before but without leaving the house, ever. Governments found the best solution to be, people staying in their houses and not having any physical contact as much as possible. In order to maintain this rule, our houses had to be capable of everything we were doing outside. We needed a way of living outside, without actually going outside. Capitalist society has managed to create consumers without the physical product itself.  All the ‘products’ are coded to feel real without it physically existing. This made it possible to keep living our old lives in a new, more technological way. I, myself am actually surprised how this has happened, I was actually expecting a more revolutionary take for the society but I guess even an extremely deadly virus is not enough for us, as humans to stop consuming. 

Of course all social gatherings, whether it is for pleasure or it is mandatory, have become virtual too. This started very primitively with just video calls where you could see and hear the people you connect with. Later we switched to creating our own avatars and go into virtual worlds, just like video games but instead of a fantasy scenario it was the boring real world. This worked for a while but something was still missing, it didn’t felt “real”. Around the year 2025, the company Nvidia developed the best virtual reality experience, ‘The Ultra Real’. By this time people has already forgotten what was their normal life like 5-6 years ago, this new ‘The Ultra Real’ life experience was beyond imagination for them. Of course it was a perfect hit, after Nvidia, companies like Oculus VR, Google, Sony, Nintendo and many more has tried to overcome and better this new technology. This technology became our sixth sense, it was a brand new experience. With this product you could travel, go on a holiday, visit your grandparents -of course if they were lucky enough to still be alive- , buy them gifts, give them gifts; basically everything you normally do, of course without leaving your house. So in order to take a part in this virtual world, all companies have recreated themselves virtually, they had products and stores made in 3D in this new world. With this development we’ve entered a new dimension to be a part of. While we were searching them all over the space, we’ve created our own inside the walls of our homes. 

Of course not all people felt the same way, some thought ‘The Ultra Real’  was no match for the real world, some thought it was a violation of privacy, of personal life.They said it was an insult to the human nature. This group of people refused to use ‘The Ultra Real’, avoided the ‘stay home’ rules, and camped in small groups at the forested lands. These groups were usually consisted by small families or friends with no virus and they weren’t welcoming outsiders into their groups with the fear of infection. There can not be a large number of these groups since the governments are not very welcoming to them. They constantly need to hide and live in a state of fear of getting caught.

The 3D printing technology developed excessively in the last 15 years. Nowadays 3D printers can print everything you can imagine of. They’ve gotten faster, there is a printer for everything, literally everything you can imagine of. Now, with this technology, instead of having shipped bought products to your address, you simply print them with 3D printers at home, this provides for many more people to stay at home. If you put the right ingredients you can “print” foods also. Now for the ingredients; A new way of eating and acquiring food has arised. Since it was dangerous to go out even for vital needs such as food, people started to plant and harvest their own food in their houses no matter if they had gardens or not. This was a huge opportunity for the agriculture market. There were already some ways to plant without earth but they needed to be improved in order to use commonly. Hydroponic agriculture has become the number one choice for everyone since it was the easiest and the most productive way to use in a house-farm. This way of farming uses water instead of earth, and it takes much less space than regular farming since it allows plants to be stackable on top of each other so it is not only cleaner, but also much more productive inside a small place. Also with some special sets you almost need to do nothing, everything gets done automatically. There is also Aeroponics, which was developed by NASA, for an efficient farming in the space. This technique dos not require any liquid or soil, but uses a special solution misted through the roots of plants.

Of course there are now much strict surveillance rules by the governments. Everyone has to have their smart watches with them 7/24. Smart watches were a thing even before the pandemic but now they has taken over the phones since it is way more convenient and has at least every features phones had. Every citizen’s ID is matched with their watch, and they’re tracked by the government for; if they go out or not. People seem to be okay with this since they are afraid for their health.

In the end we see that, even with this many thing changing in the human society, just like it did before and it will do so in the future, the gluttonous capitalism has found a way of living to itself. Although the way we live and feel has seem to be changed, many of us still live just to consume,  perhaps only the way we consume has changed, system remained the same for sure. I am quite used to the new way of living, at first it was so hard, but I adapted to it without even realizing. I can’t remember how things were used to be, if that way was better, or more enjoyable. This is just how we live now, this is our reality. With the constant thread of life outside of our homes, I am almost always surprised how well we continue to live peacefully. In the end, it is true what they say, humans will get used to anything.

