---
title: "Tongue Mark"
author: "Münevver Çelebi"
---
# Tongue Mark
by _Münevver Çelebi_

Anybody remember what happened?

We awoke and the world has changed. What year are we in? Yes that's right, 2102. I forgot. What was your day? I hit my head hard to remember, where is my watch? Haha, yes today is from the days around you ... My head ... I realized when I put my fingers behind my head, blood. How did I get hurt, what happened?

I and my team had been receiving very different and violent signals from Ganymede for a long time. Severe, persistent, and sometimes intermittent satellite signals worry us. Akay doesn't seem to take it seriously, but I realize they're pretty serious. Since daylight, the satellites were disconnecting their signals from the focal one by one, getting mixed into the deep dump of Rom, from there being sent to the Rom Recycling Center. Rom workers are tired of this situation. Collecting and recycling incoming satellite waste takes serious time. The Light Shuttle that we sent to investigate this event was out of the atmosphere and reached the satellites within seconds, but there was no apparent problem. The shuttles did not indicate any significant danger. Mr. Rohen, the manager of Rom, said that every time there was no problem, no trespassing and forbidden access to the atmosphere was visible in their system. He seems to be very confident in himself and his security systems. Although I and Akay have always warned Mr. Rohen about the inadequacy of the entry systems security measures, Mr. Rohen is a little careless as there has been no problem so far. Akay and I warned him a lot about this. "Look, Mr. Rohen, there are many aggressive and violent signals coming to the for these days, this may be an attempt to attack, only retinal and finger scanning may not be enough, we have to increase the measures!"

He didn't listen. He even found it ridiculous. Security was enough.

While I was sipping my rose tea in focal, Ganymede started to be filled with meaningless and very violent signals again. "Akay, can you see, again, one of our satellite has disappeared in Rom!" At that moment there was a terrifying explosion. A deafening bang, just as we guessed! Ganymede is shattered!
I couldn't believe my eyes, the huge satellite was destroyed! It is almost impossible for such a thing to happen by itself! All our communication satellites were shattered! How could it be, how powerful an explosion could destroy an entire satellite! Akay and I immediately proceeded to the pressure chamber and locked the doors. We could have stayed here until we realized what was happening. We understood that this was an attack attempt. While discussing who does and why it didn't take long to see the light shuttles with the Phobos country logo. Mr. Rohen and his others have declared an emergency. Could these late measures save us?

When I reached the Linza on my fingertip and looked outside, I was almost shocked by what I saw. It had been expected. Our warnings turned out to be true, security systems were not enough. The Phobos people had crossed the firewall of the atmosphere to invade our planet. Destroying satellites was the first stage of the attack. They first started by cutting off communication with other planets. We got it late. "Akay, we finally warned Mr. Rohen,"

"We should have applied the TONGUE MARK!

Finally, Phoboslu expeller found us in the pressure chamber and we were confined in a blindfolded room. I don't know how many days have passed. A grumpy came, opened our eyes, and brought some food. When I looked out of the linza, the Sun began to show its warm face more slowly. "Now you will work for us, we occupied your planet," said an expell from Phobos. The moment he said, "We have all the command!" When Akay and I asked "What do you want from us?", We received the answer "You will develop the best security measure for us! " The answer to the question "Why do we do this?" Was a simple and treacherous smile. "Because this will be the safety of your life. The notes we received indicate that you have information about the safest atmosphere access security system! 

We had no choice but to do it.


At the very least, if we made the planet's security entrance stronger, we could prevent new attacks and enemy entries, giving Mr. Rohen time to fight the Phobosites. We had to accept it and we started. There was a security company that Akay and I had already consulted, and with the Phobos commander's permission, we decided to work with that company. The name of the company is PIGNUS. A very successful company trying to reduce fingerprint and retina scanning to zero error. We talked a lot with the manager, Mr. Luis, about Tongue Mark, but he did not lean towards applicability. "The retina and fingerprint system already on the Light Shuttle is flawless, why do we need another security system?"

It was heard!


The next day, Akay and I gathered in a room to meet with Mr. Luis and his team. "You were right, we should have listened to you! We need to make the Tongue Mark system applicable immediately! "Akay was already the person who came up with this idea and had done studies and research. "The most different and impossible to imitate biological identity card found in every human being. This idea was not welcomed as it is unhealthy to lick around, but you should know that each person's Tongue Mark is different from each other. The error rate is 0%. If we safely clean the Tongue Tracepoints on the Light Shuttle, we will handle it. Actually, it is such an easy and safe method. We will record the Language Track of each Light Shuttle user in the Language Scanning system we will install on the Light Shuttle and the shuttle users will use this system when entering and exiting the planetTongue Scanning will be done with a scanning machine containing "Colorless Double Bronze Glass". This glass is the healthiest, least stained glass and reflects harmful rays. 

When the language of a person whose Language Trace was defined before is shown to the Tongue Mark scanning mechanism again, this language structure registered in the database will be automatically found and we will be informed whether that person wants to enter his shuttle from a friend or enemy planet. Any Language Trace not defined in the system will be able to enter the atmosphere"

Mr. Louis had no choice but to admit because Akay was perfectly right and her arrogance would almost end their planet.

He had researched Tongue Trace, too, but he didn't listen to Akay because licking around didn't make sense and healthy, and retina and fingerprint scans seemed safe enough for him. The Phobos commander was immediately notified and Phobos people started by applying this method on their own planet. Phobos people were busy applying this system to their own planet, but we added Strychnine to the content of the interstices we gave them to clear the Language Trail points and misnamed the glass type. This was in the wrong direction and Mr. Rohen sent the Phobosites back to where they came from with a successful war plan. PIGNUS broke the export record, put the Tongue Mark system into practice on all friendly planets, and broke records in the production of ara All friendly planets now use the Tongue Trail at the entrance to the atmosphere, Light Shuttles, and no foreign or enemy Light Shuttle users with a Tongue Trail were admitted to the planet. All the planets were safe now.


_FOCAL_: Center

_IS IN THE DAY_: Sunday

_ROM_: Space

_EXSER_: Soldier

_SURROUNDING_: Tuesday

_LİNZA_: Hole/lens viewed from the door

_NOTE_: Intelligence

_ARAS_: Disinfectant/cleaner
