---
title: "Find Your Happiness"
author: "Nazmiye Kılıç"
---
# Find Your Happiness
by _Nazmiye Kılıç_

**Abstract** 

> _In the years when the new world order, people experienced a lot of bad things in the past.  Now they have new living conditions.  Life is much more difficult for them.  In this new order, new applications have been developed for everyone to find their own happiness.  It is an important goal for people to continue to live with maximum happiness with the innovations made in many areas._

**Year: 30 November 2065**

The world is no longer the world we remember old.  Did the world we used to live in really exist?  Did we have a normal life?  Or is it all our dream?  All people are now questioning this.  How can the endless disasters we have experienced in the past and the situation we are in now become real?  How did we get like this in a very short time?

**Are We Really Good?**

According to the data released a few days ago, the world population is only two billion people.  How did we get so small? It all started with the Covid-19 epidemic that surrounded the world in 2020.  After that period, many new epidemics emerged and people could no longer fight epidemics.  After a complete epidemic, we encountered new epidemics.  There have been no new outbreaks in the past few years, but are we doing well now?  No, we are never in good shape.  Billions of people died as a result of the epidemics we experienced.  Those who are alive now bear the traces of the epidemic and people die later, just like Chernobyl.  People who lived in my house opposite died yesterday due to the continuing impact of the pandemic that ended last.

Due to the striking effect of the epidemics, people started to live alone.  People are now afraid of each other.  We have to stop meeting even with our closest ones.  I guess it wouldn't be wrong to say that everyone looks like a monster to us.  Others are more dangerous than ours now.

**Gloomy Life**

Also, the weather is very unstable due to climate changes.  The weather changes suddenly and it even rains for months.  It becomes impossible to endure months of rainfall after a while.  I'm not just talking about negativity physically.  Psychologically, one is begging for these rains to end.  Living with continuous rainy and gloomy weather for months makes me and other people like me cooler from life.  I miss the good old sunny days in rainy weather for a long time.  Actually, I miss the stable four seasons weather.

**Does Only Earth Bring Us Bad Things?**

Not only are the bad things that the world presents to us are epidemics, we have also made the world worse now.  We wasted the water and what was the result?  Now we fight each other over water.  We now take a bath every few weeks and only have the right to drink half a liter of water a day.  Yes, it rains for months, but there is also scorching heat for months.  The accumulated water is not enough for anyone.

All of this sounds horrible, right?  Especially considering the old times.  People cannot be happy with life.  Being happy and enjoying life is not easy anymore and we need to be happy now.  Is happiness really close to us?  I don't know at all but I hope it is close.

**Happiness Is Close To Us**

Despite all this, a few good news came one after another.  More hopeful developments are happening for humanity.  At least we need them so that we can continue to live and be even a little happy.  Otherwise, how can we endure so much?  Many entrepreneurs have implemented new applications in the past months.  There have been new developments in order for our new world to be more bearable and for people to have a more comfortable life.

**Alone Person**

Due to the ongoing impact of the epidemics, the rate of people living alone has increased.  People want their own personal space.  The existing houses are not enough for anyone.  With the latest innovation, portable homes that do not take up much space have been put into use.  Thanks to these houses, people can stay in movable houses within the period they determined.  These houses, which generally have everything a person may need, have different models according to consumer demand.  So they can add everything I want to these mini houses.  These houses are a good shelter for people to protect themselves from the epidemic.  They offer people the opportunity to live alone and still choose according to their tastes.  Since these houses are portable, they can be installed in different parts of the city.  So you don't have to go out of town to stay in these places.  You can stay here without getting away from the city center.  In addition, personal security is ensured due to epidemics.

**I Continue With What I Want**

Everything is easier now for students who attend school from home.  It was very difficult to continue education from home.  Thanks to the new application, students choose their own teacher characteristics and education style.  The students choose things such as the speed at which the content is taught and the method of teaching.  For example;  a student can choose a teacher who gives more examples.  He can also listen to a topic in the lesson in fast mode.  In addition, the student selects the exam or homework status.  If he chooses homework, the system sends him the appropriate homework after he chooses the criteria he wants.  Of course, the teaching profession has not come to an end here.  They prepare all the ingredients.  For example, they are preparing assignments for all homework style criteria.  There are lecturers belonging to all types of lectures determined in the system and they narrate and record accordingly.  The problem of focusing and unwillingness of students while continuing education from home, etc.  Since they have a lot of problems, they choose all the things they want in the system and receive training in accordance with it.  You decide your education in a way that you love, feel happy and understand better.  Not every student can learn in the same way or enjoy the lesson.  Each student's capacity, interests and abilities are different.  Therefore, with this application, students choose the best and happiest education method for them.  In addition, in this new method of education, there are also interview lessons for students to talk to students in different locations.  As a result of the epidemics, individualization increased and the students in the developing age became very lonely.  With these interview lessons, students will be able to continue to create a social environment by talking to foreign people.  Of course, if students are uncomfortable with the meeting, they have the right to withdraw.

**Food Is Not Just a Necessity**

Due to the continuing impact of the epidemics, some food brands have switched to new applications.  Personalized concept restaurants.  Eating places are no longer preferred in public areas.  There are private or optional dining areas for several people.  Thanks to these small venues all over the city, people can escape the permanent effect of the epidemic. The person entering the venue orders the dishes after choosing what they want from the food brands on the computer system in the space.  The ordered meals arrive at small dining venues where the person is present.  There are currently more than 20 catering companies in the system.  More brands are expected to be added soon.  People don’t only benefit from the food service in this place.  It also benefits from entertainment programs and services such as watching movies, listening to music and karaoke.  Spaces that don’t have a single shape were designed in many concepts.  Some of the concepts are: "our world in 2150", "stone age", "yellow- our new world", "we are in the past", "feel younger", "have you ever really been scared before" etc.  There are also concepts and concepts that everyone can find on a simpler level.  People choose the time they will stay at the entrance and pay a fee.  These places are preferred today, thanks to both being personal and offering many services in one place.

**Winter Like Spring**

An entrepreneur developed an application to make people less psychologically affected by long-lasting climatic conditions.  Thanks to the application, if the spring season is selected in winter, bird sounds or things suitable for the season they choose are presented to the person.  Even if the person lives in winter, thanks to the application, he can feel the season he has chosen at a high rate.  In the application, people can choose the features they want, in the season they want, from the system.  Due to climate change, a single weather condition is experienced for very long periods.  People feel better with this application because they are tired of being exposed to the same air constantly.  No matter what long weather conditions we don’t like, we can feel it in the season we want and make us happy.  With this application, all opportunities are provided for people to experience the moment where they can feel happier.  Of course, while experiencing the rainy and cold weather, the application may not physically bring us the summer season, but it can make us feel as if we are in the summer season.  In this way, it is easier to endure long seasons.  We can continue our lives with what is best for our own happines.

**Happiness**

All the innovations made allow us to feel good despite all the negativities to find our own areas despite the epidemics and to live life more easily.  The most important point of the applications is that people can find things that will make them happy even in difficult moments.
