---
title: "Betterment - Threats & New Hopes"
author: "Nihan Yıldırım"
---

# Betterment - Threats & New Hopes
by _Nihan Yıldırım_

The world is changing. As the population increases, the balance of the world deteriorates. The negativities brought about by globalization affect not only everything but also the climate.
 
The winter is always beautiful. When we think about it, we get immediately excited and the cute snow views, memories come to our mind. We beg of God to snow. But this time, everything is different... It's like we're in a science fiction movie right now. The climate is colder than it’s ever been. The air we breathe is enough to make us cold. Unusual situations occur with the deterioration of balance. Sunspots in the thermosphere are gradually decreasing. The sun is falling asleep slowly, the Thermosphere is getting colder and narrower. This causes the weather to gradually get colder, the nights getting longer and the winter seasons to be longer, and at the same time to be harder. When I look out of the window, all I see is snow. Few stars shine in the sky now. The clouds do not leave the sky even at night. Summers are also cooler. The sun is no longer as efficient as it used to be. When the fossils found at the bottom of the ocean were examined, it was found that the amount of carbon dioxide at the bottom of the oceans was higher than normal during the ice ages when the world struggled in ancient times. Normally, when the oceans release carbon dioxide into the atmosphere, the ice sheets would shrink and the amount of carbon dioxide in the atmosphere would increase. Thus, carbon dioxide would absorb the heat and cause the air to heat up. Less and less sunspots in the thermosphere mean that the oceans are pulling carbon dioxide the deeper and the planet now has to deal with harsh colds. Deep ocean waters cannot rise, meaning carbon dioxide cannot rise to the surface, now that there are more ice layers on the surface. The ice sheets are getting bigger and bigger, there is a shortage of carbon dioxide in the atmosphere. The icebergs are getting bigger, causing the sea level to drop well below normal, the temperature dropping below normal. Many small seas and lakes are now frozen. Especially the Baltic Sea, located in the north of Germany, has been frozen for months. Human-induced carbon emissions are no longer sufficient for the warming of the climate. People and animals accustomed to mild climate conditions are having a hard time. Some species even disappear. Some species may soon have to migrate to the most temperate places. Of course, if there is such a place left ... This problem poses a threat to living creatures on land as well as a major threat to marine creatures. Some creatures that cannot adapt to extremely cold waters can become extinct. There are not too many people on the outside. We think two times when we have to go outside because it’s cold as ice.
 
We get stressed when we even think about it. This situation also affects as psychologically. We try not to think about bad things and try to be positive.  We try hard to convince ourselves that everything is going to be good but we also don’t know what the future holds. We try to make it better. Another issue we need to mention is, with the increase in extreme cold, the production of many plants has become difficult. With the increase in greenhouses, global food shortages are tried to be prevented. Of course, heating the greenhouses is seen as a big problem in such a situation. This is very energy-needed work. While local heating systems are used in some of the greenhouses, electrical heating systems are used in some parts. More wind power is used for electricity generation. In these cold conditions, the excessive wind has been turned into an advantage in this way. Overall, there is great cooperation in the world. Governments play an active role in this process, cooperating to get out of this situation as early as possible. Many studies are being done to prevent the situation in a scientific sense. The National Oceanic and Atmospheric Department, which is commissioned to investigate the weather and sea events in the world by America, is working on a vehicle that will advance with ocean currents and allow the water to warm with the heat waves released into the water. In this way, the ice floes will become thinner. Thus, the ocean waters will become lighter and, with the rise, will bring excess carbon dioxide to the surface. It will take thousands of this vehicle to achieve this goal, so the authorized people work hard on this issue. We believe that they're on the edge of the glory. Of course, with all these, people's lifestyles have changed enormously. As I mentioned before, people no longer go out unless they have to. They try to take precautions as much as they can to avoid being sick. It is known that vitamin D prevents flu and similar diseases in cold weather to a great extent. Therefore, the use of vitamin D has increased. Additionally, with the difficulty of crop production, consumption is now more controlled. People no longer buy more than they need. Fashion is no longer as important as it used to be. People no longer look at how the clothes look, but whether they keep up with the weather conditions. Brands are also making great efforts to offer products suitable for these conditions and maybe little hopes. Timberland's newly released product, which can prevent many diseases such as colds and pneumonia in cold weather conditions, relieves the consumers' hearts to some extent. Timberland's newly released battery - powered boat not only measures your foot temperature but also when the temperature drops, inside warmth begins. Thus, we will be able to get rid of a little bit of sickness and cold in harsh weather conditions. Lumberjack, on the other hand, has also launched a jacket that can adjust the internal temperature according to your body temperature. In this period when heavy snowfall increases due to weather conditions, the icing on the roads is at a level that should not be taken lightly. Considering positions where only winter tires may not be enough, Volvo has launched a brand new winter tire that provides outstanding grip on road surfaces covered with snow and ice, as well as wet roads in cold conditions. In addition to the features found in other classic winter tires, this tire warms up as the car runs and softens the snow, minimizing its slipperiness. It protects us against a possible accident. Moreover, Volvo's winter tire also has more sipes than ordinary winter tires, which are more excellent for clearing water and slush from the path of the car and mitigating the risk of slipping. Burberry, one of the largest umbrella producers in the world, has designed an umbrella that can not only protect us from getting wet in snow and rain but also warm us up. Working with a rechargeable system, this umbrella helps you to warm up while you go on the road thanks to the hot air coming out of its pulleys.

This way the climates are predicted to return to normal, and that's what we want most right now. Otherwise, famine could occur and many animal and plant species could become extinct. This is a particularly big threat to endemic species. Everyone is making an effort and praying for the old warm days to come. Science is now the greatest hope, and there is always hope for everything.
