---
title: "Betterment - Wasteworlds"
author: "Öykü Tengiz"
---
# Betterment - Wasteworlds
by _Öykü Tengiz_

Dates indicate March 2053. All the chaos in the world for the last 7 years is now in order. Global warming, which has been going on for many years and no one cares, was about to end human history 7 years ago. Global warming has slowly dried up our soil over the years, and agriculture has become impossible as the soil has become unproductive. Thousands of people were forced to migrate to countries that could continue farming. But it was too late for everything. Gradually, all arable land became made of stone. We thought we had animals that we could feed on, but animals that couldn't feed on the soil were driven to death. Animals that feed on each other have killed each other. Each species was gradually becoming extinct. Despite everything, the human population was growing more and more, and the world was having trouble carrying  people. But this population growth and the disasters caused by global warming were quickly bringing about the end of humanity.

The Earth, which dried up due to global warming, and all the water resources that evaporated, took away the main things needed for humanity to live. People could no longer feed or find water to drink. In this new world order, food and drink were replacing money. The new rich were the ones whose food cabinets were full to the brim. At first, people were comfortable thinking that they would get through it, just like everything else. The number of people who were aware of the danger was very small. Brands also started selling the last provisions in stock that remained in their hands and everything that could be drunk at very exorbitant prices. Farmers engaged in agriculture were the first to starve because they were left without money. Leaders and rich people began to buy all the remaining food and drinks, paying above what was sold, and stock up on surplus needs. People became unhealthy from hunger and thirst, weakened and died, or became sick from filth. Cities began to smell of garbage, hospitals were overflowing with sick people. The gradual depletion of the food and drink supply was an unexpected disaster around the world, and everyone was about to despair.  

At some point, people began to experience psychological depressions, apart from the hunger problems they experienced from not being able to find food. Because eating isn't really just about being fed, it's about people enjoying what they eat. For this reason, they were now deprived of this feeling. If nutrition was just to satisfy vital needs, there would be no such disease as obesity in the world. for this reason, So great depressions began to occur. people wanted to eat sweet, eat meat, taste every feeling of salty, bitter, they missed the taste of food that feeling of eating.

About three years after the outbreak of events, in 2049, the situation reached a very serious level and serious reductions in the world's population began to be seen. Especially financially, the poor were unable to provide themselves and their children with the necessary nutrients to live, and therefore there were serious losses around the world. People were slowly getting up against to each other, there were clashes over the last remaining water and food. Civil wars had become inevitable. People who did not die of ill also killed each other in search of water and food. Even at this point, a disease called cannibalism began. People who missed the taste of meat and starved brain functions didn't work properly realized that there was no limit to what they could do and decided to taste human meat. People in the segment that reached this level really daredevil missed the defenseless people who came in front of them, tore them up and cooked them with pleasure. Humanity began to disappear from day by day.

Although scientists have been trying to develop a solution to this problem for many years, no results were reached until two years ago. In human experiments, dozens of people continued to die from poisoning. After five years of research, pills that will provide all our nutritional values and clean water that we can drink have started to be produced from chemicals. The Betterment process had begun. People who agreed to participate in the experiments were getting better, cleaned up, and their immunity was getting stronger. Even their psychology has seen a tremendous improvement. These pills and water first reached by important businessmen, leaders and very rich people. During the two-year period, all the brands in the food sector switched to their production. Now, from the poorest person to the richest person, everyone has access to them.

The first market-leading brand of pills was Nestle. Nestle has offered humanity a variety of pills that will leave both salty and sweet taste in your mouth. It was a worldwide revolution for a brand to put them up for sale. It was possible to find pills at any price; their nourishment and beauty of taste varied in proportion to their price. The water was the same as our good old water. After Nestle, McDonald's also began to take over the business. Many of the world-famous brands had gone bankrupt in the process. But big brands such as Nestle and McDonald's have endured this process and eventually reached wealth again. Coca Cola carried out the revolution in the field of beverages and began to produce Cola with exactly the same taste again from the chemical water produced and immediately put it for sale. After the return of water and food, celebrations, festivals were held.

In our country, too soon, Eti brand offered sweet pills for sale. Salty pills, on the other hand, began to be sold by the brands Tat and Tukaş. Damla water through Coca Cola Company and Nestle brand water were offered for sale. These pills and waters imported for the moment will soon start to be produced in our country.
