---
title: "Life Disarray After the Pandemic"
author: "Sena Duran"
---
# Life Disarray After the Pandemic
by _Sena Duran_

Life has never been the same after the epidemic called Covid-19, which emerged in 2019, increased greatly in 2020, and greatly affected every area. Although we have come to 2050, the effects of the epidemic and the negativities caused by the epidemic continue. Everything has changed in the world and people have been largely affected by this situation. 

While the epidemic continued, the economic system collapsed completely. Unemployment has emerged and people are still unemployed even now. Unemployment has spawned poverty, and the concept of tolerance has become one of the most important concepts forgotten today. People started to migrate wherever there is work because of fear of unemployment. Certain regions of the world started to grapple with environmental problems to a large extent as a result of these migrations. As the population density increased in these regions, people started killing each other to survive. Social peace, order, and security are now gone.
 
Although the private sector has shown a huge increase after the epidemic, today it is facing the threat of extinction. Likewise, the state lost its power to a great extent in this process. All humanity was deprived of its sense of security and countries had no strength to fight even with each other. People work under these conditions for very low amounts. Since many people do not accept these conditions, they are living illegally and secretly and continue their lives by stealing. The crime level increased dramatically and reached a very difficult level to stop. The economy entered into a major recession. Banks have lost their old functions, and people who can work cannot get enough salaries, so they only get their basic needs. Many workplaces and factories were closed and many people were left unemployed.
 
Unfortunately, education activities were also interrupted during this period. The right to education has become an area accessible not only to everyone but only to those who keep up with this order and are financially strong. People working with low wages started to have difficulties in providing education for their children. In this case, it caused a pause in the field of general culture and science. He got his share of this situation in art. Many different arts are unfortunately long forgotten. Some people do not even have time to listen to music or have a device to listen to. On some days, music is played in the city for people to listen to. Unfortunately, art events are no longer held, and rare events are held only for the rich.
 
In the recent past, it was said that the vaccine was available, but there was an overlooked situation. The virus completely differentiated and mutated frequently, and no vaccine was effective against this virus. As a result of the rapid change of the virus, some different diseases began to emerge in the people who were administered the vaccine. The human population currently living in the world has almost halved compared to the population in 2019 and 2020. Deaths have increased so rapidly that it is almost impossible to counter and produce remedial solutions.

Diseases caused by viruses and vaccines have penetrated human DNA permanently and the DNA structure has changed. Especially the births of women started to result in death. Nowadays, women have stopped having children because they think their babies will be stillborn or that they will die during childbirth. Sexual diseases started to appear in most men. The elderly population disappeared in 2025. The part called middle age fought the brain and muscle-bone diseases caused by the virus, and these diseases have become the most serious and dangerous diseases of our day. When the economy collapses and people begin to die of hunger and extra diseases, the health system, which has been made free, is about to disappear as a result of excessive demand and pressure. In case the health system collapses completely, the world population will face the threat of complete extinction and only those who have DNA that can adapt to the new world order will survive.

In addition to all these events, while the population of the world is decreasing rapidly, it has begun to disappear in the world as a result of the social disorder caused by people. The concentration of population in certain parts of the world has also greatly affected the use of resources. With the condensation of toxic gases in certain regions and sending them to the atmosphere, the glaciers are completely melted and due to the excessive heat of the Sun's atmosphere, the water evaporates rapidly and water resources are largely destroyed. Water wars are increasing day by day and the vast majority of people are trying to survive without water.

As a result of all these events, chaos dominated the whole world. In this process where the social order disappears and the strong survive, there is a group that tries to restore order and prosperity in ancient times. Of course, although it is impossible to return to the past after this process, it may be possible to stop people's crime rates and fears, at least in a small proportion.

One of the brands that keep up with this order and strives to resolve this current confusion is IBM. IBM, which was shown as the world giant in the software field in the past, has lost its old power in this process, but still tries to continue its work, even if it is limited. Based on the problem that technology does not reach every person, it makes a project that aims to reach people. This project aims to create a technology that measures people's emotional states and enables them to stop negative behavior before they occur.

Due to the decrease in the world population, people need money or basic living materials because of the distancing from the social order and the increase in the unemployment rate. IBM says that it will meet some of the needs of the volunteers involved in this project, and includes them in this project. In this project, when negative emotions or thoughts arise through a small chip placed on the person's body, they stop themselves through this chip. When negative emotions and thoughts are revealed, the chip activates itself as a result of the triggering of certain hormones secreted in the body and the person inevitably distances himself from that emotion. In this way, people against tendencies such as crime and violence that disrupt the social order are stopped.

Another feature of this chip is that it reads the DNA and thus detects diseases in the person's body in advance and activates the person by giving an alarm. In this way, it becomes possible to detect diseases in advance and if the treatment method is known, it is started immediately. If the disease is a newly emerging condition, people are screened and discovered by disease scientists. Because the Covid-19 virus continues to exist by mutation and evolves into new diseases, they aim to prevent diseases and increase the world population by developing this feature.
 
Although we are in 2050, life has completely changed after Covid-19. The social order and welfare of the people have disappeared. Environmental problems have increased, but solutions are being sought by a group, and these solutions have greatly positive results for those who are tried. Part of the way people stop themselves from bad behavior brought back a sense of understanding. In this way, it is possible to say that the chaos began to leave its place to calmness, even though it is very small and at the beginning level.
