---
title: "Future Theories"
author: "Şerif Yıldırım"
---
# Future Theories
by _Şerif Yıldırım_

**Abstract** 

> _This article is an estimate of the possible events we will experience by 2040. These predictions, which are created by considering the events experienced today, may be scenarios we may encounter in the future. In this study, those problems encountered in Turkey next year, economic, there are also predicted about the sociological and psychological problems._

We are in the middle of 2040, the weather was very hot, the winter was without rain again and the drought was getting closer. Most of the glaciers melted. With the effect of forest fires and concreting, rainfall was reduced. The consumer society's addiction to consumption does not only consume products but also nature. While there was the idea that a more conscious society would be formed with the increase of educated people, on the contrary, a society was formed in which the understanding of production fond of social media was to produce content and the effect of this negatively affected the whole country. The agricultural production of the country is at a very low level, the products produced are not enough for ¼ of the country. We are mostly foreign dependent on food. The monetary value of the country has plummeted and subsistence has become very difficult. The land to farm has decreased and the people who can do these jobs are now very few. City life beats village life. The rich who wanted to live in villages away from the cities started to live by building luxury houses. Villages turn into villa sites. Villages that are seen as natural habitats become urbanized and disappear. The convenience food industry has grown. The use of imported canned food has increased. People now consume even the food in their homes from ready-made products. This has been a great advantage for ready-made food manufacturers. They were working on expanding the product line. The biggest problem for them was the import of raw materials (agricultural products).

After the great Marmara earthquake in 2027, Istanbul was devastated. The expected disaster happened and there was a great loss of life and property. The favorite city of Istanbul became the city of pain. This event, which strangled the whole country, negatively affected the country economically. The population of Istanbul decreased by 500,000 with those who died. Most people migrated to other cities. Even the 15 July Martyrs Bridge (Bosphorus Bridge) was destroyed, only the pillars remained. So much so that many sectors moved their field of activity to other big cities such as Ankara. The heart of the business world was badly damaged. After this painful incident occurred in Istanbul in the construction sector in Turkey, the origin of Japanese companies, has become popular. People have seen once more painfully how important construction is. The bill for this learning has been heavy. Orphans and widows could not easily forget the sorrow of this incident. After the 2020 virus outbreak, this was the event that most of the deaths occurred in Turkey. The surrounding provinces outside of Istanbul were very affected by this earthquake.

The prosperity that will come with the promised 2023, technological innovations have not been experienced. The economic power of the country began to lose its effect in those years. The people's antipathy to the government increased. Unfortunately, it took a long time for people who thought everything would improve in a year to realize that they could not make a living economically. The products called domestic and national production were sold more expensive than imported products in the country and people were disappointed. It was increasingly difficult for people with low salaries to buy high-priced products. People who want to live the magnificent lives seen in the TV series, people who think that life consists of these scenarios fell into despair in their own lives.

When we come to 2040, the health sector was developing the most. People's health was adversely affected due to the troubles they went through and diseases were increasing. Because the prices of private drugs are so high, the public has difficulty or even cannot buy them. Devices began to be produced that treat people with electromagnetic waves and interfere with their minds. Thanks to these technologies, which are especially popular among the high society, the rich people continue their lives with a more peaceful consciousness. The lower layer was grappling with their troubles. The extreme violence against women in the 2020s, in fact, was only brought up as violence against women, but the society was so distressed that there was a tendency to violence in general. And again, in order to drive this people into chaos, they were only reflected in the media as violence against women and instilled this perception in people. The victims of violence in the country were shown as women. In fact, this thought settled in the consciousness of even those who did not use violence against women until then. Violence, which is an expression of the unrest in people, has now been replaced by suicides. In the last five years, the number of people who committed suicide has increased rapidly, as if the people were finding their way out of the crisis. The health sector has started intensive studies on this subject. Studies are carried out on drugs that will make people calmer, just like a virus vaccine.

The clothing industry has lost its popularity. Benefiting from the blessings of the consumption culture, the sector lost its appeal as the basic needs of the human being were endangered. The indulgence in fashion with a variety of clothes has left its place to an ordinary, plain style of clothing. People started to dress for need, not for competition.

Due to the increasing problem of university graduates not being able to find a job, universities did not attract as much attention as before. People who went to college to have fun time didn't have such luxury these days due to financial difficulties. In the 2020s, young people who saw that finding a job was provided with nepotism and their efforts were in vain experienced great disappointments. Years spent on education was wasted. In addition to these educations, people who realized their personal development became more successful and were able to save themselves from these troubles to some extent.

People understood the importance of nature. Everyone started planting a tree in front of their house. With these saplings sprouting among the concrete structures, it was as if people were giving their hopes up. Nature punished people, and people understood its power. If you contribute to nature, it will reward you. Trying to beat it didn't help people at all. Brands started campaigns by giving small seeds to those who buy their products. Although it may seem like a public relations work, the destruction of nature affected them negatively. It was like investment work they did. A dry nature and unhappy consumers could not help them.

Some foreign companies have transferred their production centers to Turkey. They chose this way to take advantage of people's cheap labor. Because the cheapest thing in the country was people. Many production areas were already in the hands of foreign companies. For this reason, even the production within the country was beneficial for the outside, not inward.

The media has lost its power. The number of people who are aware that the media does not reflect the truth has increased. People who saw that what was shown to them were actually hoaxes got into negative thoughts against the media. Print media is already gone. It continues on TV and internet. In recent years, many people have been fined for their posts, as the control of the shares made on personal accounts has tightened.
