---
title: "You are Being Watched"
author: "Sevil İleri"
---
# You are Being Watched!
by _Sevil İleri_

In this metaphorical article, I addressed the privacy concern that occurs in humans, and explained it with a growth and decay scenario. I talked about the solutions made on this.

How are we monitored?

Now, with developing technologies, people talk to each other with product suggestions from the keywords they talk to. This situation, which started with listening to messages and calls, left its place to listening to the environment. This situation starts with the camera system in every street, every shop. He switched to having a camera system on every screen. While we are in front of our computers, cameras evaluate our statement. The cameras on TVs are the same. In fact, just like Facebook in the past, people willingly give all this information. This seemingly innocent situation actually led to enormous privacy problems. Normally, big events are happening due to hackers who abuse the system where our statements are evaluated while looking at only a product and stealing private images. Among other rumors that the images were sold for big money.

While in the past years we were only watched with cameras on the road, we are now constantly being watched by screens inside our house. All these data come to us as data and come before us when we do shopping. When I enter a store, it appears which products I buy the most and which brands I prefer. However, this situation can be very humiliating due to the level of income. When I want to try something new, I can have problems due to the brand I bought before. Or when I want to choose the same brand, the brand suggestions I come across can leave me indecisive and I cannot shop calmly. This is happening not only in the grocery store but also in the clothing stores. Especially in clothing / electronics stores, it can sometimes be very humiliating to examine the behavior of people after looking at the tag price. Our locations are always shared live. When going to a special place, one gets really nervous. The electronic clocks we buy to measure our sleep health; getting information about our dreams.

Does the state need brands?

You think the crime rates are decreasing in a place where there is so much monitoring, but on the contrary, crime rates increase. Brands have become so powerful that police try to get information from brands for some criminals because they have the biggest data. As this is the case, trust in the police decreased. Even the trust in the state has decreased, some parties use people's data and this data is sold in the form of the black market. Unfortunately, because people cannot stop technology, these are even voluntary, but there are some security measures. XYZ company makes a name for itself with the measures it offers.

Solutions of the XYZ brand:

Security company XYZ has developed a device, so location signals can be interrupted and you are not constantly monitored. The security, where people go to watch things, differentiate from camera companies and this company, which develops devices to prevent people from being tracked, broke ground. You can carry this device with you. It both stores location information and does not allow camera views when synchronized with the devices you use. In this way, you can spend more comfortable time on your television, computer or with your phone.

Other companies' measures:

He states that he has developed special software for Microback systems and it is not possible to steal data in any way. It is a very good solution due to the distrust towards brands. I hope this software developed will be effective. Brands do not say we will stop watching you, but they say you will be monitored securely and your data will not be stolen. I believe that data theft will reach very different levels in the coming days, and we can say that more difficult days await security and the state.

Pineapple watch is; He has not yet offered a good solution for dream data. I hope this special software of microback can be a source of inspiration for them too.

What is the state doing?

It is in dispute with the state security company XYZ because it uses signal cutters not only by the common people but also by criminals. The state is hardly able to access the data now, remaining in the shadow of the brands and in trouble with the signal cutters.

Result:

People have serious privacy concerns, for the wheels of the capitalist system it appears as numbers, data, not human beings. They are only directed to consumption. The state is bleeding due to the power of brands. In the following years, it is thought that this situation can reach more serious dimensions with technology.
