---
title: "The Virtual Shopping Platform"
author: "Tolgacan Sezer"
---
# The Virtual Shopping Platform
by _Tolgacan Sezer_

**Abstract** 

> _A healthy, simple and innovative shopping experience provided by Inditex Group to its users against the risk of mutated Coronavirus._

The risk of Coronavirus is increasing and people from all over the world are psychically and psychologically harmed from the Covid-19. Most serious fears of people about Coronavirus are getting the virus and transmitting it to loved ones. That’s why they try to protect themselves and their loved ones by not staying in crowded places as much as possible. People are not the only ones protecting themselves. Against the risk of Coronavirus, governments also are trying to protect their citizens with lockdown. 

Due to both lockdown and people's avoidance of crowded places, many industries are damaged as at least as people and countries. Such as entertainment, clothing, education, sport and many more industries. They experience financial loss and try to survive. Employers and employees who work in these industries are perhaps one of the most delighted group after health workers with a good news from vaccination studies. The studies are developed practised by scientists and main of countries but unfortunately, the vaccine that will completely eliminate the risk of Coronavirus has not been found yet because the virus is mutating.

Let’s supposing that scientists still haven't found a solution to the Coronavirus due to the virus is mutating, and the year is 2025. 

With the psychological evolution that can be experienced, people will become more meticulous, more cautious, more connected to their houses and more closed to crowd places like shopping malls. In this case, a new problem will be added to the problems people have experienced since the beginning of the coronavirus. 

Some of people will meet their needs without leaving home but some of them are going to meet a new problem. People who avoid being in crowded places will not be able to go to stores and theirs fitting rooms and they can not try out clothes that tried by others, too. The people who are going to buy clothes on the internet without using them will meet the difficulties of return or exchange. Some of people will be able to excanges clothes with what they want but many of them experience very trouble in process of return or exchange because of not fitting. This will lead to brand infidelity and rapid consumer loss for brands.

Clothing brands, which will be one of the industries adversely affected by this situation, that owned stores in shopping centers are going to start get almost all of their sales share only from internet shopping. The brands that can not contact consumers face to face are not going to want to damage their financial situation with becoming unnecessary rent expenses and workers’ salary. They will start to invest in the digital world, which will become the only point of contact with the consumer.

In a shopping world where trial rooms will become history, Inditex Group which includes famous brands such as Zara, Pull and Bear, Bershka and Stradivarius will find a solution to this problem with personalization which is one of the emerging consumer trends. According to personalization, consumers expect physical spaces to recognize and react to them as individuals, but in this case the physical space will not be the store, it will be brand website.

Inditex Group, which has 7,200 stores worldwide in 2020, will close more than half due to the Coronavirus and its impact on consumer behavior, like other brands in the clothing industry. It will offer a new healthy shopping experience in order to retain their customers and attract new ones. This is exactly what people who want to realize their old habits in postmodern and healthier ways need.

The solution to be found by Inditex Group will be “the virtual shopping platform”. The brand's value proposition will be simple: healthy and simple shopping. In the virtual shopping platform, customers are going to visit store of Zara, Pull and Bear, Bershka and Stradivarius like real life, but on the mobile application or computer screen! How does? The use of the virtual shopping platform is very understandable:

1. First of all, customers will enter the site any of Zara, Pull and Bear, Bershka and Stradivarius. 

2. When customers, ie users, enter to any of these sites first time, they will encounter a screen with information that needs to be filled in, such as height, weight, body measurements, body type, face scan, e-mail address and phone number, thus create their virtual characters.

3. This information will be valid for the websites of all brands within the Inditex Group and users will not need to create their virtual characters again every time. They will able to reach their virtual characters from any smart phone or computer screen.

4. Users who will create their virtual characters are ready to shop in this point.

5. On the next screen, users will find themselves inside the store, as if in real life! Rayons, trial rooms, payment point, mirrors, everything will be as in real atmosphere.

6. With the first person camera angle on the smart phone or computer screen, users will be able to take their virtual characters wherever they want in the store, just like go around Google Street View.

7. In this virtual shopping platform, users will be able to try on their virtual characters before adding the outfit they like to the shopping basket and worrying question that  "Will it look like on me as I want?" will come to an end with healthy and simple way.

This online shopping platform, to be developed by the Inditex Group, which will not consider the effects of the Coronavirus as a threat and turns it into a hope, will reach at least 5 million people all over the world in the first 6 months. The CEO of Inditex Group will announce that sales have increased this much for the first time since 2020.

Consumers will be delighted with this creative solution that will remain popular on social media and news bulletins for a long time. Consumers will make numerous comments on social media and share photos with their new outfits that the clothes they buy from Zara, Pull and Bear, Bershka or Stradivarius on the virtual shopping platform look exactly as they imagined.

Besides the applications of Zara, Pull and Bear, Bershka and Stradivarius will become most downloaded apps at the end of 2025 on App Store and Play Store.

It appears that the virtual shopping platform provides such a great benefit to users that even if the Coronavirus risk will be completely over, it seems to continue to be in demand.
