---
title: "Brave New World"
author: "Zeynep Öykü Karagöz"
---
# Brave New World
by _Zeynep Öykü Karagöz_

**Abstract** 

> _One of the biggest personal problems of both today's world and the future: Status Seekers. Status seekers are all about having something that makes them stand out from the crowd – something special, something unique, something that expresses their personality and, preferably, something only they own._

It's 2040. 20 years ago, the whole world went through a massive pandemic process. A virus appeared in China, and people began to die from it. This virus, which is not important to the rest of the world, has spread throughout the world over time. Curfews have begun around the world to prevent the spread of the virus. In the process, people's face-to-face communications are completely over. If we remember the coronavirus process, people were deprived of face-to-face communication, workplaces and schools were online, and everyone was at home. People started looking for different types of communication, and social media caught up with their help. This process had already increased the social media addiction, which was one of the problems of the era and brought with it the discovery of the convenience of technology for all types of communication. People were with their phones and computers at every moment of their daily lives because they had no other chance to communicate with their loved ones. In those years, applications such as Instagram and Twitter were only used for sharing photos and ideas, and together with the process became the cornerstones of communication. People started share their ideas and themselves in these media. They tried to make a difference and be visible in their social media accounts. Because there was not any other option to show themselves. I said, everyone was in their homes. It was a difficult period because as a social media user, we had to see what everyone was doing and thinking every single second! The coronavirus process has been circumvented, but its social effects are still ongoing.

As you know, we are still in the process of social distance that we entered in those days. We still cannot communicate face-to-face with anyone and we still attend jobs and schools online. The only areas where we can prove ourselves, show ourselves are Instagram, Twitter and Facebook. There is only way to communicate and be a powerful human being is using these social media accounts. If I wouldn’t show myself in Instagram, I became a invisible person for everyone. No workplace sees me, no man knows me, and my friends forget about me. For a long time, no one sees each other face-to-face. There is no way out other than using these platforms.
 
Because he has all these platforms, naturally Mark Zuckerberg is now the major power in the world. Everything happens the way Mark wants it to because if he wants it, the system will crash... The government cannot do anything about it. Even governments must use these platforms, and no one has the power to stand up to Mark. Everyone on earth is trying to exist with using Mark’s medias.
 
Even economic power is in his hands. US economy is already ruined because of the new world order. Mark's fortune today is $ 560 billion… Will people oppose this new order and try to find new platforms for communication, or will everyone pray that Mark is a good person and wait for the next step?
